# New to R? Start here

If you're new to R and want to learn how to use it, this library might be a little daunting.

> There's so much choice! 

If you aren't sure where  to start, then try one these two options:

### Book: R for Data Science

This book is an excellent introduction to R programming and gets you started with visualizing data so you see some exciting stuff, and the power of R, right away. 

The book is free to read at https://r4ds.had.co.nz/

There's an accompanying exercise solution book at https://jrnold.github.io/r4ds-exercise-solutions/

For a different take on the soltuions, check out *Yet another ‘R for Data Science’ study guide* which can also be found at https://brshallo.github.io/r4ds_solutions/

### Video Course: Getting started with R

If you prefer video instruction with progress tracking, check out this course from "R for the Rest of Us" called Getting Started with R.

https://rfortherestofus.com/courses/getting-started/


### YaRrr! The Pirate’s Guide to R

[Nathaniel D. Phillips](https://twitter.com/YaRrrBook)

This book is meant to introduce you to the basic analytical tools in R, from basic coding and analyses, to data wrangling, plotting, and statistical inference.


The book is free to read at <https://bookdown.org/ndphillips/YaRrr> 
