# Book Clubs

Just like the book clubs you know and love, except that people actually talk about the book they're busy reading!

R book clubs are usually a group of people who follow along together in working though the same book, with some sort of periodic check-in (often weekly, often via video) discussing the text, exercises and solutions. 

Below is a list of book clubs. These usually have a specific start and end date, so it may happen that a book club has already ended even though it's listed here.

If you are running a book club, feel free to add it. 

## NHS-R community

If you're one of the estimated 10 000 data analysts working in the NHS or someone who works closely with the NHS or health data, here's a [blog post](https://nhsrcommunity.com/blog/nhs-r-book-club/) introducing the NHS-R Community book club. The book club is coordinated through the [NHS-R Slack Group](https://nhsrcommunity.slack.com/) and the specific channel is #book-club. Certain email addresses can just join the Slack group (like @nhs.net) but if you have an email address that needs approval please contact NHS-R Community through their contact details on the [website](https://nhsrcommunity.com/contact/). The book club has covered statistics books like The Art of Statistics by David Spiegelhalter and The Book of Why by Judea Pearl and presentations given at the meetings can be found on the [GitHub repository](https://github.com/nhs-r-community/book_group).

The Community will be coordinating another book club for the R4DS book and the channel for that is #r4ds-book-club.


## Data Science Learning Community 

(formerly the R4DS community) 

The [Data Science Learning Community](https://dslc.io/) has a number of running book clubs. Once you've joined the slack group, you can search for channels. 

They also have a channel specifically for book club facilitators!







