---
editor_options: 
  markdown: 
    wrap: 72
---

# Career & Community

These books aren't all strictly R focussed, but they do have a lot of relevance for many R programmers.


## Build Your Career in Data Science
[Emily Robinson](https://twitter.com/robinson_es) and [Jacqueline Nolis](https://twitter.com/skyetetra)

You are going to need more than technical knowledge to succeed as a data
scientist. Build a Career in Data Science teaches you what school leaves
out, from how to land your first job to the lifecycle of a data science
project, and even how to become a manager.

A lot of free preview, Paid $20

<https://www.manning.com/books/build-a-career-in-data-science>

## Conversations On Data Science

Roger Peng and Hilary Parker

This book collects many of their discussions from the podcast [**Not So
Standard Deviations**](https://soundcloud.com/nssd-podcast) and distills
them into a readable format.

Pay what you want for the ebook, minimum $0.00

<https://leanpub.com/conversationsondatascience>


## Executive Data Science

Brian Caffo, [Roger D. Peng](https://twitter.com/rdpeng), and [Jeffrey
Leek](https://twitter.com/jtleek)

A Guide to Training and Managing the Best Data Scientists. Learn what
you need to know to begin assembling and leading a data science
enterprise.

Pay what you want for the PDF, minimum $0.00

<https://leanpub.com/eds>

## Essays on Data Analysis

Roger Peng

This book draws a complete picture of the data analysis process, filling
out many details that are missing from previous presentations. It
presents a new perspective on what makes for a successful data analysis
and how the quality of data analyses can be judged.

Pay what you want for the ebook, minimum $0.00

<https://leanpub.com/dataanalysisessays>


## Getting Started in Data Science

[Ayodele Odubela](https://twitter.com/DataSciBae)

This book is for anyone intersted in Data Science, but is unsure where
to start. Cut through the noise and learn my best tips for understanding
Machine Learning with insight from my 4 years of industry experience.
Learn the math as it applies to real-life data projects and get an
understanding of fairness, ethics, and accounability in AI.

(Not R focussed but looks good so I'm adding it - Oscar :) )

Paid \~\$30

<https://gumroad.com/l/getting-started-in-data-science>

## Hiring Data Scientists and Machine Learning Engineers
[Roy Keyes](https://twitter.com/roycoding)

It's quite possible that the only thing more confusing than defining data science is actually hiring data scientists. Hiring Data Scientists and Machine Learning Engineers is a concise, practical guide to cut through the confusion. Whether you're the founder of a brand new startup, the senior vice president in charge of "digital transformation" at a global industrial company, the leader of a new analytics effort at a non-profit, or a junior manager of a machine learning team at a tech giant, this book will help walk you through the important questions you need to answer to determine what role and which skills you should hire for, how to source applicants, how to assess those applicants' skills, and how to set your new hires up for success. Special emphasis is placed on in-office vs remote hiring situations.

Paid, varies ~$34
https://leanpub.com/dshiring


## Introduction to Machine Learning Interviews Book
[Chip Huyen](https://huyenchip.com/)

This book is the result of the collective wisdom of many people who have sat on both sides of the table and who have spent a lot of time thinking about the hiring process. It was written with candidates in mind, but hiring managers who saw the early drafts told me that they found it helpful to learn how other companies are hiring, and to rethink their own process.

The book consists of two parts. The first part provides an overview of the machine learning interview process, what types of machine learning roles are available, what skills each role requires, what kinds of questions are often asked, and how to prepare for them. This part also explains the interviewers’ mindset and what kind of signals they look for.

The second part consists of over 200 knowledge questions, each noted with its level of difficulty -- interviews for more senior roles should expect harder questions -- that cover important concepts and common misconceptions in machine learning.

https://huyenchip.com/ml-interviews-book/





## Telling Stories With Data
[Rohan Alexander](https://twitter.com/RohanAlexander)

This aim of this book is to help you learn how to tell stories with data. It establishes a foundation on which you can build and share knowledge, based on data, about an aspect of the world of interest to you.

In this book we explore, prod, push, manipulate, knead, and ultimately, try to understand the implications of, data. The motto of the university from which I took my PhD is ‘Naturam primum cognoscere rerum’ or roughly ‘first to learn the nature of things,’ and we will indeed attempt to do that. But the original quote continues ‘temporis aeterni quoniam,’ or roughly ‘for eternal time,’ and it is tools, approaches, and workflows that enable you to establish lasting knowledge that I focus on in this book.

https://www.tellingstorieswithdata.com/

## Twitter for R Programmers

[Oscar Baruffa](https://twitter.com/OscarBaruffa), [Veerle van
Son](https://twitter.com/veerlevanson)

The R community is very active on Twitter. You can learn a lot about the
language, about new approaches to problems, make friends and even land a
job or next contract. It's a real-time pulse of the R community.What can
you gain from becoming active on Twitter? This book will talk about the
benefits and it will show you how to use Twitter.

<https://www.t4rstats.com>

## Twitter for Scientists

Not R-specific, but as many R users are also Scientists this book can
really help.

<https://t4scientists.com/>





## The Programmer's Brain : What every programmer needs to know about cognition
[Felienne Hermans](https://twitter.com/Felienne)

Explores the way your brain works when it’s thinking about code. In it, you’ll master practical ways to apply these cognitive principles to your daily programming life. You’ll improve your code comprehension by turning confusion into a learning tool, and pick up awesome techniques for reading code and quickly memorizing syntax. This practical guide includes tips for creating your own flashcards and study resources that can be applied to any new language you want to master. By the time you’re done, you’ll not only be better at teaching yourself—you’ll be an expert at bringing new colleagues and junior programmers up to speed.


Free & Paid ~$30

[Manning publications link](https://www.manning.com/books/the-programmers-brain?utm_source=felienne&utm_medium=affiliate&utm_campaign=book_hermans2_programmers_12_8_20&a_aid=felienne&a_bid=d7c7c538)


## Project Management Fundamentals for Data Analysts
[Oscar Baruffa](https://twitter.com/OscarBaruffa)

In Project Management Fundamentals for Data Analysts, I’ve boiled the concepts down to the bare essentials which can be read in under 15 minutes – you can certainly fit that into your crazy schedule (and it will help your future schedule not be so chaotic!).

These concepts can be used to great effect on their own if you wish to never read another word on the topic. It’ll also provide a solid foundation if you want to dive deeper into more formal courses or sophisticated theory.

Paid $15
https://oscarbaruffa.com/pm/


# Archeology
## How To Do Archaeological Science Using R
Ben Marwick (editor)

Archaeological science is becoming increasingly complex, and progress in this area is slowed by critical limitation of journal articles lacking the space to communicate new methods in enough detail to allow others to reproduce and reuse new research. One solution to this is to use a programming language such as R to analyse archaeological data, with authors sharing their R code with their publications to communicate our methods. This practice is becoming widespread in many other disciplines, but few archaeologists currently know how to use R or have an opportunity to learn during their training. In this forum we tackle this problem by discussing ubiquitous research methods of immediate relevance to most archaeologists, by using interactive, live-coded demonstrations of R code by archaeologists who program with R. Topics include getting data into R, working with C14 dates, spatial analysis and map-making, conducting simulations, and exploratory data visualizations.

https://benmarwick.github.io/How-To-Do-Archaeological-Science-Using-R/

## Quantitative Methods in Archaeology Using R


The first hands-on guide to using the R statistical computing system written specifically for archaeologists. It shows how to use the system to analyze many types of archaeological data. Part I includes tutorials on R, with applications to real archaeological data showing how to compute descriptive statistics, create tables, and produce a wide variety of charts and graphs. Part II addresses the major multivariate approaches used by archaeologists, including multiple regression (and the generalized linear model); multiple analysis of variance and discriminant analysis; principal components analysis; correspondence analysis; distances and scaling; and cluster analysis. Part III covers specialized topics in archaeology, including intra-site spatial analysis, seriation, and assemblage diversity.


Loan or buy ~$100
[Cambridge COre site](https://www.cambridge.org/core/books/quantitative-methods-in-archaeology-using-r/DEAE593FA2418EA3B8ECD538C34ED2D5?fbclid=IwAR0guclfEtttfDkVKNUJWfhQ1wgUlXSKAIA3f_6D3hS_9EkUKivSY9AyFD8)

# Big Data

## Exploring, Visualizing, and Modeling Big Data with R

[Okan Bulut](https://twitter.com/drokanbulut), [Christopher
Desjardins](https://github.com/cddesja)

Working with BIG DATA requires a particular suite of data analytics
tools and advanced techniques, such as machine learning (ML). Many of
these tools are readily and freely available in R. This full-day session
will provide participants with a hands-on training on how to use data
analytics tools and machine learning methods available in R to explore,
visualize, and model big data.

<https://okanbulut.github.io/bigdata/>

## Mastering Spark with R

Javier Luraschi, Kevin Kuo, Edgar Ruiz

In this book you will learn how to use Apache Spark with R. The book
intends to take someone unfamiliar with Spark or R and help you become
proficient by teaching you a set of tools, skills and practices
applicable to large-scale data science.

PS the first chapter has a Jon Snow quote ;)

<https://therinspark.com/>

# Blogdown

## blogdown: Creating Websites with R Markdown

We introduce an R package, blogdown, in this short book, to teach you
how to create websites using R Markdown and Hugo.

<https://bookdown.org/yihui/blogdown/>

## Create, Publish, and Analyze Personal Websites Using R and RStudio
[Danny Morris](https://r4sites-book.netlify.app/get-help.html#connect-with-me)

A free, digital handbook with step-by-step instructions for launching your own personal website using R, RStudio, and other freely available technologies including GitHub, Hugo, Netlify, and Google Analytics.

https://r4sites-book.netlify.app/



# Bookdown

## bookdown: Authoring Books and Technical Documents with R Markdown

This short book introduces an R package, bookdown, to change your
workflow of writing books. It should be technically easy to write a
book, visually pleasant to view the book, fun to interact with the book,
convenient to navigate through the book, straightforward for readers to
contribute or leave feedback to the book author(s), and more
importantly, authors should not always be distracted by typesetting
details.

<https://bookdown.org/yihui/bookdown/>

## A Minimal Book Example

This is a sample book written in Markdown.

<https://benmarwick.github.io/bookdown-ort/>

# Data Science

## R for Data Science

[Hadley Wickham](https://twitter.com/hadleywickham) [Garret
Grolemund](https://twitter.com/StatGarrett)

This is the website for "R for Data Science". This book will teach you
how to do data science with R: You'll learn how to get your data into R,
get it into the most useful structure, transform it, visualise it and
model it. In this book, you will find a practicum of skills for data
science. Just as a chemist learns how to clean test tubes and stock a
lab, you'll learn how to clean data and draw plots---and many other
things besides. These are the skills that allow data science to happen,
and here you will find the best practices for doing each of these things
with R. You'll learn how to use the grammar of graphics, literate
programming, and reproducible research to save time. You'll also learn
how to manage cognitive resources to facilitate discoveries when
wrangling, visualising, and exploring data.

<https://r4ds.had.co.nz/>

## R for Data Science Solutions

Solutions for the hadley and Grolemund R4Ds book

<https://jrnold.github.io/r4ds-exercise-solutions/>

*Yet another 'R for Data Science' study guide*

An alternative set of solutions for R4Ds.

<https://brshallo.github.io/r4ds_solutions/>




## Everyday Data Science
Andrew Carr

Everyday data science is a collection of tools and techniques you can use to master data science in your day-to-day life. There are case studies, tutorials, code snippets, pictures, math, and jokes. All designed as a fun introduction to the world of data science. Some example chapters include, A/B testing to make perfect lemonade, word vectors to improve your resume, differential equations for weight loss, and how a man used statistics to qualify for the Olympics. Life is full of decisions. We, as people, have the remarkable ability to make decisions in the face of uncertainty. We, as humans, have only recently developed the ability to use computers to process vast amounts of data to improve our decision making. This innovation has led to the development of the field of Data Science. This book is written to give tools and inspiration to aspiring decision makers. You make decisions daily and the methodology of data science can help.


Paid ~$8
https://gumroad.com/l/everydaydata


## An Introduction to Data Analysis
Michael Franke

his book provides basic reading material for an introduction to data analysis. It uses R to handle, plot and analyze data. After covering the use of R for data wrangling and plotting, the book introduces key concepts of data analysis from a Bayesian and a frequentist tradition. This text is intended for use as a first introduction to statistics for an audience with some affinity towards programming, but no prior exposition to R.

https://michael-franke.github.io/intro-data-analysis/index.html


## Introduction to Data Science

Rafael A Irizarry

The demand for skilled data science practitioners in industry, academia,
and government is rapidly growing. This book introduces concepts and
skills that can help you tackle real-world data analysis challenges. It
covers concepts from probability, statistical inference, linear
regression, and machine learning. It also helps you develop skills such
as R programming, data wrangling with dplyr, data visualization with
ggplot2, algorithm building with caret, file organization with
UNIX/Linux shell, version control with Git and GitHub, and reproducible
document preparation with knitr and R markdown.

<https://rafalab.github.io/dsbook/>

Pay what you want for PDF, minimum \$0.00

<https://leanpub.com/datasciencebook>

## Data Science: A First Introduction

[Tiffany-Anne Timbers](https://twitter.com/TiffanyTimbers) Trevor
Campbell Melissa Lee

This is an open source textbook aimed at introducing undergraduate
students to data science. It was originally written for the University
of British Columbia's DSCI 100 - Introduction to Data Science course. In
this book, we define data science as the study and development of
reproducible, auditable processes to obtain value (i.e., insight) from
data.

<https://ubc-dsci.github.io/introduction-to-datascience/>

## Data Science at the Command Line, 2e
Jeroen Janssens

This book is about doing data science at the command line. Our aim is to make you a more efficient and productive data scientist by teaching you how to leverage the power of the command line.

https://www.datascienceatthecommandline.com/2e/

## Practical Data Science with R, Second Edition

Nina Zumel and John Mount

Practical Data Science with R, Second Edition takes a practice-oriented
approach to explaining basic principles in the ever expanding field of
data science. You'll jump right to real-world use cases as you apply the
R programming language and statistical analysis techniques to carefully
explained examples based in marketing, business intelligence, and
decision support.

<https://www.manning.com/books/practical-data-science-with-r-second-edition#toc>

## R Programming for Data Science

Roger Peng

This book is about the fundamentals of R programming. You will get
started with the basics of the language, learn how to manipulate
datasets, how to write functions, and how to debug and optimize code.
With the fundamentals provided in this book, you will have a solid
foundation on which to build your data science toolbox.

<https://bookdown.org/rdpeng/rprogdatascience/>

## Exploratory Data Analysis... by Roger D. Peng

Roger Peng

This book teaches you to use R to effectively visualize and explore
complex datasets. Exploratory data analysis is a key part of the data
science process because it allows you to sharpen your question and
refine your modeling strategies. This book is based on the
industry-leading Johns Hopkins Data Science Specialization

Pay what you want, minimum \$0.00

<https://leanpub.com/exdata>

## edav.info/

Zach Bogart, Joyce Robbins

With this resource, we try to give you a curated collection of tools and
references that will make it easier to learn how to work with data in R.

In addition, we include sections on basic chart types/tools so you can
learn by doing.

There are also several walkthroughs where we work with data and discuss
problems as well as some tips/tricks that will help you.

<https://edav.info/>

## APS 135: Introduction to Exploratory Data Analysis with R

Dylan Z. Childs

This is the online course book for the Introduction to Exploratory Data
Analysis with R component of APS 135, a module taught by the Department
and Animal and Plant Sciences at the University of Sheffield. You will
be introduced to the R ecosystem.You will learn how to use R to carry
out data manipulation and visualisation.This book provides a foundation
for learning statistics later on.

<https://dzchilds.github.io/eda-for-bio/>

## The Art of Data Science

[Roger D. Peng](https://twitter.com/rdpeng) and Elizabeth Matsui

A Guide for Anyone Who Works with Data

This book describes the process of analyzing data. The authors have
extensive experience both managing data analysts and conducting their
own data analyses, and this book is a distillation of their experience
in a format that is applicable to both practitioners and managers in
data science. Printed copies are available through
[Lulu](https://www.lulu.com/content/paperback-book/the-art-of-data-science/18733039).

Pay what you want for the ebook, minimum \$0.00

<https://leanpub.com/artofdatascience>

## The Elements of Data Analytic Style

[Jeffrey Leek](https://twitter.com/jtleek)

Data analysis is at least as much art as it is science. This book is
focused on the details of data analysis that sometimes fall through the
cracks in traditional statistics classes and textbooks. It is based in
part on the authors blog posts, lecture materials, and tutorials.

Pay what you want for the ebook, minimum \$0.00

<https://leanpub.com/datastyle>

## Beginning Data Science in R

[Thomas Mailund](https://twitter.com/ThomasMailund)

Beginning Data Science in R details how data science is a combination of
statistics, computational science, and machine learning. You'll see how
to efficiently structure and mine data to extract useful patterns and
build mathematical models. Those with some data science or analytics
background, but not necessarily experience with the R programming
language

Paid, \~\$40

<https://amzn.to/2Ns1HHi>


## A Business Analyst’s Introduction to Business Analytics
[Adam Fleischhacker](https://twitter.com/preposterior)

This textbook goes farther than just teaching you to make computational models using software or mathematical models using statistics. It teaches you how to align computational and mathematical models with real-world scenarios; empowering you to communicate with and leverage the expertise of business stakeholders while using modern software stacks and statistical workflows. In this book, you do not learn business analytics to make models; you learn business analytics to add tangible value in the real-world.

https://www.causact.com/


## Business Case Analysis with R - Simulation Tutorials to Support Complex Business Decisions

[Robert D. Brown III](https://twitter.com/InciteDecisions)

Business case analysis, often conducted in spreadsheets, exposes decision makers to additional risks that arise just from the use of the spreadsheet environment. This book discusses how to use the statistical programming language R to develop a business case simulation and analysis. It presents a methodology that minimizes decision delay by focusing stakeholders on what matters most and suggests pathways for minimizing the risk in strategic and capital allocation decisions.

Apress/Springer-Nature eBook \$24.99, Softcover \$34.99

<https://www.apress.com/us/book/9781484234945#>

Amazon Kindle Rent \$14, Buy \~$19, Paperback \$24.99

<https://www.amazon.com/Business-Case-Analysis-Simulation-Tutorials-ebook/dp/B07B6Q7TK1/>


## Business Intelligence with R

[Dwight Barry](https://twitter.com/healthstatsdude)

A desktop reference for busy professionals, giving you fingertip access
to a variety of BI analytic methods done in R as simply as possible.

All proceeds will support mitochondrial disorder research at Seattle
Children's Hospital.

Free or up to \$20 for a good cause!

<https://leanpub.com/businessintelligencewithr>

## R Data Science Quick Reference

[Thomas Mailund](https://twitter.com/ThomasMailund)

In this book, you'll learn about the following APIs and packages that
deal specifically with data science applications: readr, dibble,
forecasts, lubridate, stringr, tidyr, magnittr, dplyr, purrr, ggplot2,
modelr, and more.

Paid, \~\$30

<https://amzn.to/2WN1mQy>


## Modern Data Science with R
Benjamin S. Baumer, Daniel T. Kaplan, and Nicholas J. Horton

This book is intended for readers who want to develop the appropriate skills to tackle complex data science projects and “think with data” (as coined by Diane Lambert of Google). The desire to solve problems using data is at the heart of our approach.

We acknowledge that it is impossible to cover all these topics in any level of detail within a single book: Many of the chapters could productively form the basis for a course or series of courses. Instead, our goal is to lay a foundation for analysis of real-world data and to ensure that analysts see the power of statistics and data analysis. After reading this book, readers will have greatly expanded their skill set for working with these data, and should have a newfound confidence about their ability to learn new technologies on-the-fly.

This book was originally conceived to support a one-semester, 13-week undergraduate course in data science. We have found that the book will be useful for more advanced students in related disciplines, or analysts who want to bolster their data science skills. At the same time, Part I of the book is accessible to a general audience with no programming or statistics experience.

https://mdsr-book.github.io/mdsr2e/



## Modern Statistics with R

[Måns Thulin](https://twitter.com/mansthulin)

This book covers the fundamentals of data science and statistics. The
first half deals with the basics of R and R coding, data wrangling,
exploratory data analysis and more advandced programming. The second
half deals with modern statistics (favouring permutation tests, the
bootstrap and Bayesian methods over traditional asymptotic methods),
regression models and predictive modelling. It also contains information
about debugging and explanations of 25 commonly encountered error
messages in R. In addition, there are 170 or so exercises with fully
worked solutions.

<http://www.modernstatisticswithr.com/>

## Model-Based Clustering and Classification for Data Science

[Charles Bouveyron](https://twitter.com/cbouveyron), [Gilles
Celeux](https://www.imo.universite-paris-saclay.fr/~celeux/), [T.
Brendan Murphy](https://twitter.com/tbmurphy), and [Adrian E.
Raftery](https://twitter.com/AdrianRaftery1)

Among the broad field of statistical and machine learning, model-based
techniques for clustering and classification have a central position for
anyone interested in exploiting those data. This text book focuses on
the recent developments in model-based clustering and classification
while providing a comprehensive introduction to the field. It is aimed
at advanced undergraduates, graduates or first year PhD students in data
science, as well as researchers and practitioners.

<https://math.unice.fr/~cbouveyr/MBCbook/>

# Data Visualization

## ggplot2: Elegant Graphics for Data Analysis

Hadley Wickham

ggplot2 is an R package for producing statistical, or data, graphics.
Unlike most other graphics packages, ggplot2 has an underlying grammar,
based on the Grammar of Graphics (Wilkinson 2005), that allows you to
compose graphs by combining independent components. This makes ggplot2
powerful. Rather than being limited to sets of pre-defined graphics, you
can create novel graphics that are tailored to your specific problem.

<https://ggplot2-book.org/>

## A ggplot2 Tutorial for Beautiful Plotting in R

[Cédric Sherer](https://twitter.com/CedScherer)

(Oscar: Not a book per se, but it should be, so I'm adding !)

A mega tutorial of creating great ggplot2 visuals.

<https://cedricscherer.netlify.app/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/>

## ggplot2 in 2

Lucy D'Agostino McGowan

Pay what you want, minimum \$4.99

Really good overview of ggplot2. The premise is that you'll cover the
fundamentals in 2 hours. Oscar Baruffa made a sped-up
[screencast](https://youtu.be/_G7_J8M9588) while working through it. It
did take 2 hours :).

<https://leanpub.com/ggplot2in2>

## Data Visualization - A practical introduction

[Kieran Healy](https://twitter.com/kjhealy)

This book is a hands-on introduction to the principles and practice of
looking at and presenting data using R and ggplot.

The book is free online.

<https://socviz.co/>

## Data Processing & Visualization

This document provides some tools, demonstrations, and more to make data
processing, programming, modeling, visualization, and presentation
easier.While the programming language focus is on R, where applicable
(which is most of the time), Python notebooks are also available,.

<https://m-clark.github.io/data-processing-and-visualization/>

## Data Visualization in R

Brooke Anderson

Workshop for the 2019 Navy and Marine Corps Public Health Conference. I
have based this workshop on examples for you to try yourself, because
you won't be able to learn how to program unless you try it out. I've
picked example data that I hope will be interesting to Navy and Marine
Corp public health researchers and practitioners.

<https://geanders.github.io/navy_public_health/index.html#prerequisites>

## Data Visualization with R

Rob Kabakoff

This book helps you create the most popular visualizations - from quick
and dirty plots to publication-ready graphs. The text relies heavily on
the ggplot2 package for graphics, but other approaches are covered as
well.

<https://rkabacoff.github.io/datavis/>

## Data visualisation using R, for researchers who don’t use R
[Emily Nordmann](https://twitter.com/emilynordmann), [Phil McAleer](https://twitter.com/McAleerP), [Wilhelmiina Toivo](https://twitter.com/wtoivo1), [Helena Paterson](https://twitter.com/PatersonHelena), [Lisa DeBruine](https://twitter.com/LisaDeBruine)

In this tutorial, we aim to provide a practical introduction to data visualisation using R, specifically aimed at researchers who have little to no prior experience of using R. First we detail the rationale for using R for data visualisation and introduce the “grammar of graphics” that underlies data visualisation using the ggplot package. The tutorial then walks the reader through how to replicate plots that are commonly available in point-and-click software such as histograms and boxplots, as well as showing how the code for these “basic” plots can be easily extended to less commonly available options such as violin-boxplots.

https://psyteachr.github.io/introdataviz/


## R Graphics Cookbook, 2nd edition

The goal of the cookbook is to provide solutions to common tasks and
problems in analyzing data.

The book is free online.

<https://r-graphics.org/>

## plotly Interactive web-based data visualization with R, plotly, and shiny

Carson Sievert

In this book, you'll gain insight and practical skills for creating
interactive and dynamic web graphics for data analysis from R. It makes
heavy use of plotly for rendering graphics, but you'll also learn about
other R packages that augment a data science workflow, such as the
tidyverse and shiny. Along the way, you'll gain insight into best
practices for visualization of high-dimensional data, statistical
graphics, and graphical perception.

<https://plotly-r.com/>

## Hands-On Data Visualization: Interactive Storytelling from Spreadsheets to Code

Jack Dougherty, Ilya Ilyankou

(Oscar: looks like am amazing resource and includes code templates!)

In this book, you'll learn how to create true and meaningful data
visualizations through chapters that blend design principles and
step-by-step tutorials, in order to make your information-based analysis
and arguments more insightful and compelling. Just as sentences become
more persuasive with supporting evidence and source notes, your
data-driven writing becomes more powerful when paired with appropriate
tables, charts, or maps. Words tell us stories, but visualizations show
us data stories by transforming quantitative, relational, or spatial
patterns into images. When visualizations are well-designed, they draw
our attention to what is most important in the data in ways that would
be difficult to communicate through text alone.

<https://handsondataviz.org/>

## BBC Visual and Data Journalism cookbook for R graphics

At the BBC data team, we have developed an R package and an R cookbook
to make the process of creating publication-ready graphics in our
in-house style using R's ggplot2 library a more reproducible process, as
well as making it easier for people new to R to create graphics.

<https://bbc.github.io/rcookbook/>

## Fundamentals of Data Visualization

[Claus Wilke](https://twitter.com/ClausWilke)

The book is meant as a guide to making visualizations that accurately
reflect the data, tell a story, and look professional.

The book is free online.

<https://clauswilke.com/dataviz/>

## Graphical Data Analysis with R

[Antony Unwin](http://www.gradaanwr.net/author/)

The main aim of the book is to show, using real datasets, what
information graphical displays can reveal in data. The target readership
includes anyone carrying out data analyses who wants to understand their
data using graphics.

The book is published by CRC Press and [available to
purchase](https://www.routledge.com/Graphical-Data-Analysis-with-R/Unwin/p/book/9781498715232),
but all the examples and code are freely available on a comprehensive
website accompanying the text at <http://www.gradaanwr.net/>

## JavaScript for R

[John Coene](https://john-coene.com)

Learn how to build your own data visualisation packages, improve shiny
with JavaScript, and use JavaScript for computations.

Freely available online, paid print.

<https://javascript-for-r.com>

# Field specific

## Analyzing Financial and Economic Data with R

Marcelo S. Perlin

Not surprisingly, fields with abundant access to data and practical
applications, such as economics and finance, it is expected that a
graduate student or a data analyst has learned at least one programming
language that allows him/her to do his work efficiently. Learning how to
program is becoming a requisite for the job market.

<https://www.msperlin.com/afedR/>

## Computer-age Calculus with R

Daniel Kaplan

R is closely associated with statistics, but not with calculus. It turns
out that R is an excellent language for doing calculus.

This book shows how to do common calculus calculations using R.

<https://dtkaplan.github.io/RforCalculus/>


## Crime by the Numbers: A Criminologist’s Guide to R
[Jacob Kaplan](https://twitter.com/JacobKaplanCrim)

This book introduces the programming language R and is meant for undergrads or graduate students studying criminology. R is a programming language that is well-suited to the type of work frequently done in criminology - taking messy data and turning it into useful information. While R is a useful tool for many fields of study, this book focuses on the skills criminologists should know and uses crime data for the example data sets.

https://crimebythenumbers.com/


## Data Science in Education Using R

Ryan A. Estrellado, Emily A. Bovee, Jesse Mostipak, Joshua M. Rosenberg,
and Isabella C. Velásquez

Dear Data Scientists, Educators, and Data Scientists who are Educators:

This book is a warm welcome and an invitation. If you're a data
scientist in education or an educator in data science, your role isn't
exactly straightforward. This book is our contribution to a growing
movement to merge the paths of data analysis and education. We wrote
this book to make your first step on that path a little clearer and a
little less scary.

<https://datascienceineducation.com/>

## Data Skills for Reproducible Science

[PsyTeachR team, University of Glasgow](https://psyteachr.github.io/)

This course provides an overview of skills needed for reproducible
research and open science using the statistical programming language R.
Students will learn about data visualisation, data tidying and
wrangling, archiving, iteration and functions, probability and data
simulations, general linear models, and reproducible workflows. Learning
is reinforced through weekly assignments that involve working with
different types of data.

<https://psyteachr.github.io/msc-data-skills/>


## Discrete Data Analysis with R: Visualization and Modeling Techniques for Categorical and Count Data
Michael Friendly, David Meyer

Presents an applied treatment of modern methods for the analysis of categorical data, both discrete response data and frequency data.

It explains how to use graphical methods for exploring data, spotting unusual features, visualizing fitted models, and presenting results.

Paid ~$80
http://ddar.datavis.ca/



## Learning Microeconometrics with R

Christopher P. Adams

This book provides an introduction to the field of microeconometrics
through the use of R. The focus is on applying current learning from the
field to real world problems. It uses R to both teach the concepts of
the field and show the reader how the techniques can be used. It is
aimed at the general reader with the equivalent of a bachelor's degree
in economics, statistics or some more technical field. It covers the
standard tools of microeconometrics, OLS, instrumental variables,
Heckman selection and difference in difference. In addition, it
introduces bounds, factor models, mixture models and empirical Bayesian
analysis.

Paid \~\$100
<https://www.routledge.com/Learning-Microeconometrics-with-R/Adams/p/book/9780367255381>

## Public Policy Analytics: Code & Context for Data Science in Government
Ken Steif, Ph.D

The goal of this book is to make data science accessible to social scientists and City Planners, in particular. I hope to convince readers that one with strong domain expertise plus intermediate data skills can have a greater impact in government than the sharpest computer scientist who has never studied economics, sociology, public health, political science, criminology etc.

https://urbanspatial.github.io/PublicPolicyAnalytics/

## Handbook of Regression Modeling in People Analytics

[Keith McNulty](https://twitter.com/dr_keithmcnulty)

It is the author's firm belief that all people analytics professionals
should have a strong understanding of regression models and how to
implement and interpret them in practice, and the aim with this book is
to provide those who need it with help in getting there.

<http://peopleanalytics-regression-book.org/index.html>

For accompanying solutions to some of the questions

<https://keithmcnulty.github.io/peopleanalytics-regression-book/solutions/>

## R for Excel users
Julie Lowndes & Allison Horst

This course is for Excel users who want to add or integrate R and RStudio into their existing data analysis toolkit. It is a friendly intro to becoming a modern R user, full of tidyverse, RMarkdown, GitHub, collaboration & reproducibility.

https://rstudio-conf-2020.github.io/r-for-excel/


## R Programming with Minecraft

Brooke Anderson, Karl Broman, Gergely Daróczi, Mario Inchiosa, David
Smith, and Ali Zaidi

Minecraft is awesome fun, especially in creative mode, where you can
build all sorts of crazy stuff. But ambitious building projects can be
really tedious to create by hand. With the miner R package, you can
write R code to manipulate your Minecraft world and create even more
awesome stuff.

Here's an introduction Rstats NYC conference talk on it:
<https://www.youtube.com/watch?v=r_JgPF8MJpY>

<https://kbroman.org/miner_book/?s=09>


## R for SEO
[François Joly](https://twitter.com/tuf)

Even though R'  is a terrific option for SEO, there are simply not enough resources out there. 
This guide is not here to deliver a course about R, there are plenty already. This guide is meant to be as practical as possible. How things should be done in an "R-ish way" is not the purpose of this guide. Grab what you want to grab and feel free to submit your own solution.

https://www.rforseo.com/

## R for Water Resources Data Science
[Ryan Peek](https://ryanpeek.org/) and [Rich Pauloo](https://www.richpauloo.com/)

Consists of 2 courses

Introductory: 
This course is most relevant and targeted at folks who work with data, from analysts and program staff to engineers and scientists. This course provides an introduction to the power and possibility of a reproducible programming language (R) by demonstrating how to import, explore, visualize, analyze, and communicate different types of data. Using water resources based examples, this course guides participants through basic data science skills and strategies for continued learning and use of R.

Intermediate:
In this course, we will move more quickly, assume familiarity with basic R skills, and also assume that the participant has working experience with more complex workflows, operations, and code-bases. Each module in this course functions as a “stand-alone” lesson, and can be read linearly, or out of order according to your needs and interests. Each module doesn’t necessarily require familiarity with the previous module.

This course emphasizes intermediate scripting skills like iteration, functional programming, writing functions, and controlling project workflows for better reproducibility and efficiency. Approaches to working with more complex data structures like lists and timeseries data, the fundamentals of building Shiny Apps, pulling water resources data from APIs, intermediate mapmaking and spatial data processing, integrating version control in projects with git.

https://www.r4wrds.com/


## Technical Foundations of Informatics

Michael Freeman and Joel Ross

This book covers the foundation skills necessary to start writing
computer programs to work with data using modern and reproducible
techniques. It requires no technical background. These materials were
developed for the INFO 201: Technical Foundations of Informatics course
taught at the University of Washington Information School; however they
have been structured to be an online resource for anyone hoping to learn
to work with information using programmatic approaches.

<https://info201.github.io/>

## An introduction to quantitative analysis of political data in R

[Erik Gahner Larsen](https://twitter.com/erikgahner) & [Zoltán
Fazekas](https://twitter.com/fazol)

In this book, we aim to provide an easily accessible introduction to R
for the collection, study and presentation of different types of
political data. Specifically, the book will teach you how to get
different types of political data into R and manipulate, analyze and
visualize the output. In doing this, we will not only teach you how to
get existing data into R, but also how to collect your own data.

<http://qpolr.com/>

## Machine Learning for Factor Investing

[Guillaume Coqueret](https://twitter.com/g_coqueret) and [Tony
Guida](https://twitter.com/TonyGUIDA_Quant)

This book is intended to cover some advanced modelling techniques
applied to equity investment strategies that are built on firm
characteristics.

<http://www.mlfactor.com/>

## Introduction to Econometrics with R

Christoph Hanck, Martin Arnold, Alexander Gerber, and Martin Schmelzer

Instead of confronting students with pure coding exercises and
complementary classic literature like the book by Venables & Smith
(2010), we figured it would be better to provide interactive learning
material that blends R code with the contents of the well-received
textbook Introduction to Econometrics by Stock & Watson (2015) which
serves as a basis for the lecture.

<https://www.econometrics-with-r.org/>

## How to be a modern scientist

[Jeffrey Leek](https://twitter.com/jtleek)

A book about how to be a scientist the modern, open-source way. The face
of academia is changing. It is no longer sufficient to just publish or
perish. We are now in an era where Twitter, Github, Figshare, and Alt
Metrics are regular parts of the scientific workflow. Here I give high
level advice about which tools to use, how to use them, and what to look
out for. This book is appropriate for scientists at all levels who want
to stay on top of the current technological developments affecting
modern scientific careers.

Pay what you want for the ebook, minimum \$0.00

<https://leanpub.com/modernscientist>

## Cryptocurrency Research: Open Source R Tutorial

Riccardo (Ricky) Esclapon --
[LinkedIn](https://www.linkedin.com/in/esclaponriccardo/), [Personal
Website](https://resclapon.com/)

John Chandler Johnson --
[LinkedIn](https://www.linkedin.com/in/john-chandler-johnson-361a666/)

Kai R. Larsen --
[LinkedIn](https://www.linkedin.com/in/kai-r-larsen-4413a01/),
[ResearchGate](https://www.researchgate.net/profile/Kai_Larsen)

**What you will learn**:

R: The tutorial is in R. For those without experience programming in R
we have a [high-level
version](https://cryptocurrencyresearch.org/high-level) to help you
learn before attempting the full version. Scroll down for a [breakdown
of the individual
sections](https://cryptocurrencyresearch.org/index.html#sections) for an
overview of what you will learn throughout.

Tidyverse: You will get more familiar with tools from the tidyverse,
including [dplyr](https://dplyr.tidyverse.org/),
[ggplot2](https://ggplot2.tidyverse.org/),
[tibble](https://tibble.tidyverse.org/), and
[purrr](https://purrr.tidyverse.org/). These tools provide an excellent
complete ecosystem to do data science in R.

Machine Learning: You will learn to [create machine learning
models](https://cryptocurrencyresearch.org/predictive-modeling.html) and
how to fairly [assess their
performance](https://cryptocurrencyresearch.org/model-validation-plan.html).

Cryptocurrency Data: You will learn these tools analyzing the latest
cryptocurrency data. The tutorial automatically refreshes every 12 hours
and the data is publicly available and refreshed hourly.

This tutorial is free and you can access it via
<https://cryptocurrencyresearch.org/>.

# Getting, cleaning and wrangling data

## A Beginner's Guide to Clean Data - beginners-guide-to-clean-data

Benjamin Greve

This book will help you to become a better data scientist by showing you
the things that can go wrong when working with data - particularly
low-quality data. A key difference between a junior and a senior data
scientist is the awareness of potential pitfalls. The experienced data
scientist will expect them, navigate around them and avoid costly
iteration cycles. After reading this book, you will be able to spot data
quality problems and deal with them before they can break your work,
saving yourself a lot of time.

<https://b-greve.gitbook.io/beginners-guide-to-clean-data/>

## 21 Recipes for Mining Twitter Data with rtweet

Bob Rudis

The recipes contained in this book use the rtweet package by Michael W.
Kearney.

<https://rud.is/books/21-recipes/>

## Text Mining with R

[Julia Silge](https://twitter.com/juliasilge) and [David
Robinson](https://twitter.com/drob)

This book serves as an introduction of text mining using the tidytext
package and other tidy tools in R. The functions provided by the
tidytext package are relatively simple; what is important are the
possible applications. Thus, this book provides compelling examples of
real text mining problems.

<https://www.tidytextmining.com/>

## Spreadsheet Munging Strategies

Duncan Garmonsway

This is a work-in-progress book about getting data out of spreadsheets,
no matter how peculiar. The book is designed primarily for R users who
have to extract data from spreadsheets and who are already familiar with
the tidyverse. It has a cookbook structure, and can be used as a
reference, but readers who begin in the middle might have to work
backwards from time to time.

<https://nacnudus.github.io/spreadsheet-munging-strategies/>

# Geospatial

## Geocomputation with R

Robin Lovelace, Jakub Nowosad, Jannes Muenchow

This is the online home of Geocomputation with R, a book on geographic
data analysis, visualization and modeling.

<https://geocompr.robinlovelace.net/>

## Geospatial Health Data: Modeling and Visualization with R-INLA and Shiny

Paula Moraga

This book describes spatial and spatio-temporal statistical methods and
visualization techniques to analyze georeferenced health data in R.
After a detailed introduction of geospatial data, the book shows how to
develop Bayesian hierarchical models for disease mapping and apply
computational approaches such as the integrated nested Laplace
approximation (INLA) and the stochastic partial differential equation
(SPDE) to analyze areal and geostatistical data.

<https://www.paulamoraga.com/book-geospatial/>

## Introduction to Spatial Data Programming with R

[Michael Dorman](https://twitter.com/MichaelDorman84)

This book introduces processing and analysis methods for working with
spatial data in R. The book is composed of two parts. The *first* part
gives an overview of the basic syntax and usage of the R language,
required before we can start working with spatial data. The *second*
part then covers spatial data workflows, including how to process
rasters, vector layers, and both of them together, as well as two
selected advanced topics: spatio-temporal data and spatial
interpolation.

<https://geobgu.xyz/r>


## Spatial Data Science

Edzer Pebesma, Roger Bivand

This book introduces and explains the concepts underlying spatial data:
points, lines, polygons, rasters, coverages, geometry attributes, data
cubes, reference systems, as well as higher-level concepts including how
attributes relate to geometries and how this affects analysis.

<https://keen-swartz-3146c4.netlify.app/>

## Spatial Modelling for Data Scientists
Francisco Rowe and Dani Arribas-Bel

This is the website for “Spatial Modeling for Data Scientists”. This is a course taught by Dr. Francisco Rowe and Dr. Dani Arribas-Bel in the Second Semester of 2020/21 at the University of Liverpool, United Kingdom. You will learn how to analyse and model different types of spatial data as well as gaining an understanding of the various challenges arising from manipulating such data.

https://gdsl-ul.github.io/san/


## Spatial Microsimulation with R
[Robin Lovelace](https://www.robinlovelace.net/) and [Morgane Dumont](https://directory.unamur.be/staff/modumont)

Imagine a world in which data on companies, households and governments were widely available. Imagine, further, that researchers and decision-makers acting in the public interest had tools enabling them to test and model such data to explore different scenarios of the future. People would be able to make more informed decisions, based on the best available evidence. In this technocratic dreamland pressing problems such as climate change, inequality and poor human health could be solved.

These are the types of real-world issues that we hope the methods in this book will help to address. Spatial microsimulation can provide new insights into complex problems and, ultimately, lead to better decision-making. By shedding new light on existing information, the methods can help shift decision-making processes away from ideological bias and towards evidence-based policy.

https://spatial-microsim-book.robinlovelace.net/index.html


## Predictive Soil Mapping with R

[Tom Hengl](https://opengeohub.org/people/tom-hengl) and [Robert A.
MacMillan](https://opengeohub.org/people/bob-macmillan)

Predictive Soil Mapping (PSM) with R explains how to import, process and
analyze soil data in R using the state-of-the-art soil and Machine
Learning packages with ultimate objective to produce most objective
spatial predictions of soil numeric and factor-type variables. Especial
focus has been put on using R in combination with the Open Source GIS
such as GDAL, SAGA GIS and similar, and on using Machine Learning
packages ranger, xgboost, SuperLearner and similar. This book is
licensed under a Creative Commons Attribution-ShareAlike 4.0
International License. Contributions of new chapters are welcome.

<https://soilmapper.org>

## Using R for Digital Soil Mapping

Malone, Brendan P., Minasny, Budiman, McBratney, Alex B.

Describes in detail, with ample exercises, how digital soil mapping is
done This work includes a number of work-flows that direct users how to
create digital soil maps for their own projects This work includes
tutorials for users to learn the fundamentals of R, but with a focus on
how to use it for digital soil mapping

Paid \~\$90

<https://www.springer.com/gp/book/9783319443256>


# Journalism

## Practical R for Mass Communication and Journalism

Sharon Machlis

Welcome to this excerpt from Practical R for Mass Communication and
Journalism. In these sample chapters, you'll:

learn how to find your way around R and RStudio, see how much you can do
in just a few lines of code, start doing some basic data exploration,
and get some ideas and sample code for using R in analyzing election
results. I hope you find this excerpt useful! If you do and would like
to read more, you can order the complete book from CRC Press or Amazon.

Free samples. Full paid product \~ \$55

<http://www.machlis.com/R4Journalists/index.html>

## Using R for Data Journalism

Andrew Ba Tran

This site will help you learn how to use the statistical computing and
graphics language R to enhance your data analysis and reporting process.

It was originally part of a free MOOC offered by the Knight Center at
the University of Texas

<https://learn.r-journalism.com/en/>

# Life Sciences

## An Open Compendium of Soil Datasets
Tomislav Hengl 

(Not R specific but looks really relevant)

This is a public compendium of global, regional, national and sub-national soil samples and/or soil profile datasets (points with Observations and Measurements of soil properties and characteristics). Datasets listed here, assuming compatible open license, are afterwards imported into the Global compilation of soil chemical and physical properties and soil classes and eventually used to create a better open soil information across countries. The specific objectives of this initiative are:

To enable data digitization, import and binding + harmonization,
To accelerate research collaboration and networking,
To enable development of more accurate / more usable global and regional soil property and class maps (typically published via https://OpenLandMap.org),

https://opengeohub.github.io/SoilSamples/


## Assigning cell types with SingleR

[Aaron
Lun](([\<https://osca.bioconductor.org/contributors.html\>](https://osca.bioconductor.org/contributors.html){.uri})

This book covers the use of SingleR, one implementation of an automated
annotation method for cell type annotation.

[\<https://bioconductor.org/books/3.12/SingleRBook/\>](https://bioconductor.org/books/3.12/SingleRBook/){.uri}

## Data Science for the Biomedical Sciences
Daniel Chen, Anne Brown

We hope this book provides a gentle introduction to data science. The main goal is to understand how to work with spreadsheet data and how data can be manipulated for multiple purposes. If nothing else, the book hopes to help you plan how to structure your own datasets for your own analysis. Even if you never go on to program on your own, understanding the way data can be manipulated and having a plan for your own dataset in the processing pipeline, will go a long ways when leaning and doing the analysis on your own, and/or working with collegues and collaborators on a project.

https://ds4biomed.tech/



## Using R for Bayesian Spatial and Spatio-Temporal Health Modeling
By Andrew B. Lawson

Progressively more and more attention has been paid to how location affects health outcomes. The area of disease mapping focusses on these problems, and the Bayesian paradigm has a major role to play in the understanding of the complex interplay of context and individual predisposition in such studies of disease. Using R for Bayesian Spatial and Spatio-Temporal Health Modeling provides a major resource for those interested in applying Bayesian methodology in small area health data studies.

Paid ~$100
https://www.routledge.com/Using-R-for-Bayesian-Spatial-and-Spatio-Temporal-Health-Modeling/Lawson/p/book/9780367490126

## Computational Genomics with R

[Altuna Akalin](https://twitter.com/AltunaAkalin)

The aim of this book is to provide the fundamentals for data analysis
for genomics. We developed this book based on the computational genomics
courses we are giving every year.

[\<http://compgenomr.github.io/book/\>](http://compgenomr.github.io/book/){.uri}

## Data Analysis for the Life Sciences

Rafael A Irizarry and Michael I Love

Data analysis is now part of practically every research project in the
life sciences. In this book we use data and computer code to teach the
necessary statistical concepts and programming skills to become a data
analyst. Instead of showing theory first and then applying it to toy
examples, we start with actual applications.

Pay what you want for the ebook, minimum \$0.00

<https://leanpub.com/dataanalysisforthelifesciences>

[Accompanying website](http://genomicsclass.github.io/book/)

## Data Analysis and Visualization in R for Ecologists
François Michonneau & Auriel Fournier 

Data Carpentry’s aim is to teach researchers basic concepts, skills, and tools for working with data so that they can get more done in less time, and with less pain. The lessons below were designed for those interested in working with ecology data in R.

This is an introduction to R designed for participants with no programming experience. These lessons can be taught in a day (~ 6 hours). They start with some basic information about R syntax, the RStudio interface, and move through how to import CSV files, the structure of data frames, how to deal with factors, how to add/remove rows and columns, how to calculate summary statistics from a data frame, and a brief introduction to plotting. The last lesson demonstrates how to work with databases directly from R.

This lesson assumes no prior knowledge of R or RStudio and no programming experience.

https://datacarpentry.org/R-ecology-lesson/

## R for applied epidemiology and public health
[EpiR authors](https://twitter.com/epiRhandbook)

This handbook is produced by a collaboration of epidemiologists from around the world drawing upon experience with organizations including local, state, provincial, and national health agencies, the World Health Organization (WHO), Médecins Sans Frontières / Doctors without Borders (MSF), hospital systems, and academic institutions.

Written by epidemiologists, for epidemiologists.

https://epirhandbook.com/



## Git and Github for Advanced Ecological Data Analysis

Alexa Fredston

This material was prepared for a three-hour virtual session to teach Git
and Github to a graduate-level course on Advanced Ecological Data
Analysis taught at Rutgers University by Malin Pinsky and Rachael
Winfree. (However, the only course-specific material is Section 4; the
rest should be applicable to any reader.)

<https://afredston.github.io/learn-git/learn-git.html>

## R for Health Data Science

by [Ewan Harrison](https://twitter.com/ewan_harrison) and [Riinu Pius](https://twitter.com/_Riinu_)

In this age of information, the manipulation, analysis and interpretation of data have become a fundamental part of professional life. Nowhere more so than in the delivery of healthcare. From the understanding of disease and the development of new treatments, to the diagnosis and management of individual patients, the use of data and technology are now an integral part of the business of healthcare.

Those working in healthcare interact daily with data, often without realising it. The conversion of this avalanche of information to useful knowledge is essential for high-quality patient care. An important part of this information revolution is the opportunity for everybody to become involved in data analysis. This democratisation is driven in part by the open source software movement – no longer do we require expensive specialised software to do this.

The statistical programming language, R, is firmly at the heart of this.

This book will take an individual with little or no experience in data science all the way through to the execution of sophisticated analyses. We emphasise the importance of truly understanding the underlying data with liberal use of plotting, rather than relying on opaque and possibly poorly understood statistical tests. There are numerous examples included that can be adapted for your own data, together with our own R packages with easy-to-use functions.

https://argoshare.is.ed.ac.uk/healthyr_book/

## Hydroinformatics at VT
[JP Gannon](https://twitter.com/jp_gannon)

This bookdown contains the notes and most exercises for a course on data analysis techniques in hydrology using the programming language R. The material will be updated each time the course is taught. If new topics are added, the topics they replace will be left, in case they are useful to others.

https://vt-hydroinformatics.github.io/


## R for Conservation and Development Projects: A Primer for Practitioners
Nathan Whitmore

This book is aimed at conservation and development practitioners who need to learn and use R in a part-time professional context. It gives people with a non-technical background a set of skills to graph, map, and model in R. It also provides background on data integration in project management and covers fundamental statistical concepts. The book aims to demystify R and give practitioners the confidence to use it.

Key Features:

• Viewing data science as part of a greater knowledge and decision making system
• Foundation sections on inference, evidence, and data integration
• Plain English explanations of R functions
• Relatable examples which are typical of activities undertaken by conservation and development organisations in the developing world
• Worked examples showing how data analysis can be incorporated into project reports

Paid ~$60
https://www.routledge.com/R-for-Conservation-and-Development-Projects-A-Primer-for-Practitioners/Whitmore/p/book/9780367205485

## R for Water Resources Data Science
[Ryan Peek](https://ryanpeek.org/) and [Rich Pauloo](https://www.richpauloo.com/)

Consists of 2 courses

Introductory: 
This course is most relevant and targeted at folks who work with data, from analysts and program staff to engineers and scientists. This course provides an introduction to the power and possibility of a reproducible programming language (R) by demonstrating how to import, explore, visualize, analyze, and communicate different types of data. Using water resources based examples, this course guides participants through basic data science skills and strategies for continued learning and use of R.

Intermediate:
In this course, we will move more quickly, assume familiarity with basic R skills, and also assume that the participant has working experience with more complex workflows, operations, and code-bases. Each module in this course functions as a “stand-alone” lesson, and can be read linearly, or out of order according to your needs and interests. Each module doesn’t necessarily require familiarity with the previous module.

This course emphasizes intermediate scripting skills like iteration, functional programming, writing functions, and controlling project workflows for better reproducibility and efficiency. Approaches to working with more complex data structures like lists and timeseries data, the fundamentals of building Shiny Apps, pulling water resources data from APIs, intermediate mapmaking and spatial data processing, integrating version control in projects with git.

https://www.r4wrds.com/


## Reproducible Medical Research with R
Peter D.R. Higgins, MD, PhD, MSc

This is a book for anyone in the medical field interested in analyzing the data available to them to better understand health, disease, or the delivery of care. This could include nurses, dieticians, psychologists, and PhDs in related fields, as well as medical students, residents, fellows, or doctors in practice.
I expect that most learners will be using this book in their spare time at night and on weekends, as the health training curricula are already packed full of information, and there is no room to add skills in reproducible research to the standard curriculum. This book is designed for self-teaching, and many hints and solutions will be provided to avoid roadblocks and frustration. Many learners find themselves wanting to develop reproducible research skills after they have finished their training, and after they have become comfortable with their clinical role. This is the time when they identify and want to address problems faced by patients in their practice with the data they have before them. This book is for you.

https://bookdown.org/pdr_higgins/rmrwr/



## Modern Statistics for Modern Biology

Susan Holmes, Wolfgang Huber

The aim of this book is to enable scientists working in biological
research to quickly learn many of the important ideas and methods that
they need to make the best of their experiments and of other available
data.

<https://www.huber.embl.de/msmb/>

## Orchestrating Single-Cell Analysis with Bioconductor

[Aaron Lun, Robert Amezquita, Stephanie Hicks, Raphael
Gottardo](https://osca.bioconductor.org/contributors.html)

This is the website for "Orchestrating Single-Cell Analysis with
Bioconductor", a book that teaches users some common workflows for the
analysis of single-cell RNA-seq data (scRNA-seq).

<https://osca.bioconductor.org/>

## Statistics in R for Biodiversity Conservation Paperback

by Carl Smith , [Antonio Uzal](https://twitter.com/antonio_uzal) , Mark
Warren

A practical handbook to introduce data analysis and model fitting using
R to ecologists and conservation biologists. The book is aimed at
undergraduate and post-graduate students and provides access to datasets
and RScript.

Paid product \~\$10

<https://www.amazon.co.uk/dp/B08HBLYHQL/ref=cm_sw_r_cp_apa_i_g0luFb86PXJ9Z>

## Numerical Ecology with R

by Daniel Borcard, François Gillet, [Pierre
Legendre](http://adn.biol.umontreal.ca/~numericalecology/indexEn.html)

This new edition of Numerical Ecology with R guides readers through an
applied exploration of the major methods of multivariate data analysis,
as seen through the eyes of three ecologists. It provides a bridge
between a textbook of numerical ecology and the implementation of this
discipline in the R language. The book begins by examining some
exploratory approaches.

eBook \~\$60

<https://www.springer.com/us/book/9783319714035>

## Introduction to Data Analysis with R

by [Jannik Buhr](https://jmbuhr.de/)

This is a video lecture series with accompanying lecture script that is designed to read much like a book.
The lecture is held in English for biochemists at Heidelberg University, Germany, but the examples covered are no specific to life sciences in order to enable a focus on learning the techniques with R.

free

<https://jmbuhr.de/dataIntro20/>

## WEHI Intro to Tidy R Course

by [Brendan Ansell](https://brendanansell.net)

A complete beginner's introduction to tidy R for data transformation, visualization and analysis automation — with applications in experimental biology.  
This book is based on a short course developed for biomedical scientists at the WEHI Medical Research Institute. The content is designed to make learners comfortable with using R for exploratory analysis of large data sets, but does not cover statistics. The material and teaching examples draw on popular (non-biological) data sets, as well as gene expression and drug screening data types. 

Free

<https://bookdown.org/ansellbr/WEHI_tidyR_course_book/>


## Experimental Design for Laboratory Biologists: Maximising Information and Improving Reproducibility

[Stanley E. Lazic](https://stanlazic.github.io/)

This practical guide shows biologists how to design reproducible experiments that have low bias, high precision, and results that are widely applicable. With specific examples using both cell cultures and model organisms, it shows how to plan a successful experiment. It demonstrates how to control biological and technical factors that can introduce bias or add noise, and covers rarely discussed topics such as graphical data exploration, choosing outcome variables, data quality control checks, and data pre-processing. It also shows how to use R for analysis, and is designed for those with no prior experience. This is an ideal guide for anyone conducting lab-based biological research.

~$52 USD

<https://stanlazic.github.io/EDLB.html>


# Machine Learning

## Hands-On Machine Learning with R

Bradley Boehmke & Brandon Greenwell

This book provides hands-on modules for many of the most common machine
learning methods to include:

Generalized low rank models, Clustering algorithms, Autoencoders,
Regularized models, Random forests, Gradient boosting machines, Deep
neural networks, Stacking / super learners and more!

<https://bradleyboehmke.github.io/HOML/>

## Feature Engineering and Selection: A Practical Approach for Predictive Models

Max Kuhn and Kjell Johnson

The goals of Feature Engineering and Selection are to provide tools for
re-representing predictors, to place these tools in the context of a
good predictive modeling framework, and to convey our experience of
utilizing these tools in practice.

<http://www.feat.engineering/index.html>

## Interpretable Machine Learning

[Christoph Molnar](https://twitter.com/ChristophMolnar)

A Guide for Making Black Box Models Explainable

[Online book](https://christophm.github.io/interpretable-ml-book/)

Pay what you want for the ebook, minimum \$0.00

[Leanpub PDF](https://leanpub.com/interpretable-machine-learning)

## Explanatory Model Analysis

Responsible, Fair and Explainable Predictive Modeling with examples in R
and Python

[Przemyslaw Biecek](https://github.com/pbiecek), Tomasz Burzykowski

Free online: <https://pbiecek.github.io/ema/>

Or paid printed:
<https://www.routledge.com/Explanatory-Model-Analysis-Explore-Explain-and-Examine-Predictive-Models/Biecek-Burzykowski/p/book/9780367135591>

## Supervised Machine Learning for Text Analysis in R

[Emil Hvitfeldt](https://twitter.com/Emil_Hvitfeldt), [Julia
Silge](https://twitter.com/juliasilge)

Modeling as a statistical practice can encompass a wide variety of
activities. This book focuses on supervised or predictive modeling for
text, using text data to make predictions about the world around us. We
use the tidymodels framework for modeling, a consistent and flexible
collection of R packages developed to encourage good statistical
practice.

<https://smltar.com/>

## Lightweight Machine Learning Classics with R
Marek Gagolewski

In this book we will take an unpretentious glance at the most fundamental algorithms that have stood the test of time and which form the basis for state-of-the-art solutions of modern AI, which is principally (big) data-driven.

https://lmlcr.gagolewski.com/



## Machine Learning for Factor Investing

[Guillaume Coqueret](https://twitter.com/g_coqueret) and [Tony
Guida](https://twitter.com/TonyGUIDA_Quant)

This book is intended to cover some advanced modelling techniques
applied to equity investment strategies that are built on firm
characteristics.

<http://www.mlfactor.com/>

## Mathematics and Programming for Machine Learning with R: From the Ground Up 1st Edition, Kindle

[William B. Claster](https://twitter.com/BillOita?s=09)

Based on the author's experience in teaching data science for more than
10 years, Mathematics and Programming for Machine Learning with R: From
the Ground Up reveals how machine learning algorithms do their magic and
explains how these algorithms can be implemented in code. It is designed
to provide readers with an understanding of the reasoning behind machine
learning algorithms as well as how to program them. Written for novice
programmers, the book progresses step-by-step, providing the coding
skills needed to implement machine learning algorithms in R.

Paid \~\$40
<https://www.amazon.com/Mathematics-Programming-Machine-Learning-Ground-ebook-dp-B08JHDCX9Y/dp/B08JHDCX9Y/ref=mt_other?_encoding=UTF8&me=&qid=1610095251>

## The caret Package

[Max Kuhn](mxkuhn@gmail.com)

The caret package (short for Classification And REgression Training) is
a set of functions that attempt to streamline the process for creating
predictive models.

This book is free online.

<https://topepo.github.io/caret/index.html>

## A Minimal rTorch Book

Alfonso R. Reyes

Practically, you can do everything you could with PyTorch within the R
ecosystem.

<https://f0nzie.github.io/rtorch-minimal-book/>

## Model-Based Clustering and Classification for Data Science

[Charles Bouveyron](https://twitter.com/cbouveyron), 
[Gilles Celeux](https://www.imo.universite-paris-saclay.fr/~celeux/),
[T. Brendan Murphy](https://twitter.com/tbmurphy), and 
[Adrian E. Raftery](https://twitter.com/AdrianRaftery1)

Among the broad field of statistical and machine learning, model-based techniques for clustering and classification have a central position for anyone interested in exploiting those data. This text book focuses on the recent developments in model-based clustering and classification while providing a comprehensive introduction to the field. It is aimed at advanced undergraduates, graduates or first year PhD students in data science, as well as researchers and practitioners.

<https://math.unice.fr/~cbouveyr/MBCbook/>


## Tidy Modeling with R

[Max Kuhn](https://twitter.com/topepos) and [Julia
Silge](https://twitter.com/juliasilge)

This book provides an introduction to how to use the tidymodels suite of
packages to create models using a tidyverse approach and encourages good
methodology and statistical practice throughout demonstrated using
series of applied examples.

This book is free online (currently a work in progress).

<https://www.tmwr.org/>

## mlr3 book

[Michel Lang](https://twitter.com/michellangts?lang=en)

The mlr3 package and
[ecosystem](https://github.com/mlr-org/mlr3/wiki/Extension-Packages)
provide a generic, object-oriented, and extensible framework for
classification, regression, survival analysis, and other machine
learning tasks for the R language. They do not implement any learners,
but provide a unified interface to many existing learners in R.

The book is free and work in progress. <https://mlr3book.mlr-org.com/>

# Network analysis

## Network Analysis in R Cookbook

Sacha Epskamp

<http://sachaepskamp.com/files/Cookbook.html>


## Statistical Analysis of Network Data with R
Kolaczyk, Eric D., Csárdi, Gábor

This book is the first of its kind in network research. It can be used as a stand-alone resource in which multiple R packages are used to illustrate how to conduct a wide range of network analyses, from basic manipulation and visualization, to summary and characterization, to modeling of network data. The central package is igraph, which provides extensive capabilities for studying network graphs in R. 
 
Paid ~$65
https://www.springer.com/us/book/9781493909834#otherversion=9781493909827

## Awesome network analysis

Not a book, but a compendium of resources that look really valuable. 

https://github.com/briatte/awesome-network-analysis


# Packages

## The caret Package

[Max Kuhn](mxkuhn@gmail.com)

The caret package (short for Classification And REgression Training) is
a set of functions that attempt to streamline the process for creating
predictive models.

This book is free online.

<https://topepo.github.io/caret/index.html>


## ComplexHeatmap Complete Reference

[Zuguang Gu](https://github.com/jokergoo)

The ComplexHeatmap package is used to generate heatmap visualizations. It is a
highly flexible tool to arrange multiple heatmaps and supports various
annotation graphics for high-dimensional data. These visualizations are
efficient to visualize visualizations between different sources of data sets
and reveal potential patterns.

This book here contains the full documentation to using the ComplexHeatmap
package effectively with plenty of small and complex examples to help you
create your own complex heatmap data vizualization.

<https://jokergoo.github.io/ComplexHeatmap-reference/book/>


## data.table in R – The Complete Beginners Guide
Selva Prabhakaran 

data.table is a package is used for working with tabular data in R. It provides the efficient data.table object which is a much improved version of the default data.frame. It is super fast and has intuitive and terse syntax. If you know R language and haven’t picked up the data.table package yet, then this tutorial guide is a great place to start.

https://www.machinelearningplus.com/data-manipulation/datatable-in-r-complete-guide/


## GT Cookbook

[Thomas Mock](https://twitter.com/thomas_mock)

This cookbook attempts to walk through many of the example usecases for gt, and provide useful commentary around the use of the various gt functions. The full gt documentation has other more succinct examples and full function arguments.

For advanced use cases, make sure to check out the Advanced Cookbook


https://themockup.blog/static/gt-cookbook.html


## Highcharter Cookbook
Tom Bishop

Highcharter is an R implementation of the highcharts javascript library, enabled by R’s htmlwidgets package. Most of the highcharts functionality is implemented through highcharter however the documentation is a little light. This guide will provide examples on how to create and customise various graphs whilst providing some tips on how to think about the package that will help you build and debug your more ambitious charts. 

https://www.tmbish.me/lab/highcharter-cookbook/

## The lidR package
Jean-Romain Roussel, Tristan R.H. Goodbody, Piotr Tompalski

lidR is an R package for manipulating and visualizating airborne laser scanning (ALS) data with an emphasis on forestry applications. The package is entirely open source and is integrated within the geospatial R ecosytem (i.e. raster, sp, sf, rgdal etc.). This guide has been written to help both the ALS novice, as well as seasoned point cloud processing veterans.

https://jean-romain.github.io/lidRbook/


## A Minimal rTorch Book

Alfonso R. Reyes

Practically, you can do everything you could with PyTorch within the R
ecosystem.

<https://f0nzie.github.io/rtorch-minimal-book/>

## The Tidyverse Cookbook

Edited by Garrett Grolemund

This book collects code recipes for doing data science with R's
tidyverse. Each recipe solves a single common task, with a minimum of
discussion.

<https://rstudio-education.github.io/tidyverse-cookbook/>


## The targets R Package User Manual
Will Landau

The targets package is a Make-like pipeline toolkit for Statistics and data science in R. With targets, you can maintain a reproducible workflow without repeating yourself. targets learns how your pipeline fits together, skips costly runtime for tasks that are already up to date, runs only the necessary computation, supports implicit parallel computing, abstracts files as R objects, and shows tangible evidence that the results match the underlying code and data.

https://books.ropensci.org/targets/



# Reports: R Markdown and knitr

## R Markdown: The Definitive Guide

[Yihui Xie](https://yihui.org/), [J. J.
Allaire](https://github.com/jjallaire), [Garrett
Grolemund](https://twitter.com/StatGarrett)

The first official book authored by the core R Markdown developers that
provides a comprehensive and accurate reference to the R Markdown
ecosystem. With R Markdown, you can easily create reproducible data
analysis reports, presentations, dashboards, interactive applications,
books, dissertations, websites, and journal articles, while enjoying the
simplicity of Markdown and the great power of R and other languages.

<https://bookdown.org/yihui/rmarkdown/>

## R Markdown Cookbook

[Yihui Xie](https://yihui.org/), [Christophe
Dervieux](https://twitter.com/chrisderv), [Emily
Riederer](https://twitter.com/emilyriederer)

This book showcases short, practical examples of lesser-known tips and
tricks to helps users get the most out of these tools. After reading
this book, you will understand how R Markdown documents are transformed
from plain text and how you may customize nearly every step of this
processing. For example, you will learn how to dynamically create
content from R code, reference code in other documents or chunks,
control the formatting with customer templates, fine-tune how your code
is processed, and incorporate multiple languages into your analysis.

<https://bookdown.org/yihui/rmarkdown-cookbook/>

## Getting used to R, RStudio, and R Markdown

Chester Ismay

This resource is designed to provide new users to R, RStudio, and R
Markdown with the introductory steps needed to begin their own
reproducible research. A review of many of the common R errors
encountered (and what they mean in layman's terms) will also provided be
provided.

<https://bookdown.org/chesterismay/rbasics/>

## Report Writing for Data Science in R

[Roger D. Peng](https://twitter.com/rdpeng)

This book teaches the fundamental concepts and tools behind reporting
modern data analyses in a reproducible manner. As data analyses become
increasingly complex, the need for clear and reproducible report writing
is greater than ever.

Pay what you want for the ebook, minimum \$0.00

<https://leanpub.com/reportwriting>

## Introduction to R Markdown

Michael Clark

The goal is for you to be able to get quickly started with your own
document, and understand the possibilities available to you. You will
get a feel for the basic mechanics at play, as well as have ideas on how
to customize the result to your own tastes.

<https://m-clark.github.io/Introduction-to-Rmarkdown/>

## RMarkdown for Scientists

Nicholas Tierney

This is a book on rmarkdown, aimed for scientists. It was initially
developed as a 3 hour workshop, but is now developed into a resource
that will grow and change over time as a living book.

<https://rmd4sci.njtierney.com/>

## Pimp my RMD: a few tips for R Markdown

Yan Holtz

R markdown creates interactive reports from R code. This post provides a
few tips I use on a daily basis to improve the appearance of output
documents.

<https://holtzy.github.io/Pimp-my-rmd/>

## knitr

[Yihui Xie](https://yihui.org/)

Dynamic documents with R and knitr!

The knitr package was designed to be a transparent engine for dynamic
report generation with R, solve some long-standing problems in Sweave,
and combine features in other add-on packages into one package.

The book is free online.

<https://yihui.org/knitr/>

## Reproducible Research with R and RStudio

By Christopher Gandrud

This book present all the Tools for Gathering and Analyzing Data and
Presenting Results Reproducible Research with R and RStudio through
practical examples.

The book can be reproduced by using the R package bookdown

<https://github.com/christophergandrud/Rep-Res-Book>

Also, you can buy the copy.

<https://www.routledge.com/Reproducible-Research-with-R-and-RStudio/Gandrud/p/book/9780367143985>

# R package development

## R packages

[Hadley Wickham](https://twitter.com/hadleywickham), [Jenny
Bryan](https://twitter.com/JennyBryan)

Packages are the fundamental units of reproducible R code. They include
reusable R functions, the documentation that describes how to use them,
and sample data. In this section you'll learn how to turn your code into
packages that others can easily download and use. Writing a package can
seem overwhelming at first. So start with the basics and improve it over
time. It doesn't matter if your first version isn't perfect as long as
the next version is better.

<https://r-pkgs.org/>

## rOpenSci Packages: Development, Maintenance, and Peer Review

[rOpenSci](https://twitter.com/ropensci) software review editorial team

This book is a package development guide for authors, maintainers,
reviewers and editors of rOpenSci.

<https://devguide.ropensci.org/index.html>

## HTTP testing in R

[Scott Chamberlain](https://twitter.com/sckottie), [Maëlle
Salmon](https://twitter.com/ma_salmon)

This book is meant to be a free, central reference for developers of R
packages accessing web resources, to help them have a faster and more
robust development. Our aim is to develop an useful guidance to go with
the great recent tools that vcr, webmockr, httptest and presser are.

<https://books.ropensci.org/http-testing/>

# R programming

## Best Coding Practices for R

[Vikram Singh Rawat](https://twitter.com/Guru_GyanKhoji)

R is a huge language and I would like to share the little knowledge I have in the subject. I don’t claim to be an expert but this book will guide you in the right path wherever possible.

Most of the books about R programming language will tell you what are the possible ways to do one thing in R. This book will only tell you one way to do that thing correctly.


https://bookdown.org/content/d1e53ac9-28ce-472f-bc2c-f499f18264a3/

## Book of R: A First Course in Programming and Statistics
Tilman M. Davies

The Book of R is a comprehensive, beginner-friendly guide to R, the world’s most popular programming language for statistical analysis. Even if you have no programming experience and little more than a grounding in the basics of mathematics, you’ll find everything you need to begin using R effectively for statistical analysis.

You’ll start with the basics, like how to handle data and write simple programs, before moving on to more advanced topics, like producing statistical summaries of your data and performing statistical tests and modeling. You’ll even learn how to create impressive data visualizations with R’s basic graphics tools and contributed packages, like ggplot2 and ggvis, as well as interactive 3D visualizations using the rgl package.

Paid ~$40
https://nostarch.com/bookofr


## Modern R with the tidyverse

Bruno Rodrigues

This book can be useful to different audiences. If you have never used R
in your life, and want to start, start with Chapter 1 of this book.
Chapter 1 to 3 are the very basics, and should be easy to follow up to
Chapter 9. Starting with Chapter 9, it gets more technical, and will be
harder to follow. But I suggest you keep on going, and do not hesitate
to contact me for help if you struggle! Chapter 9 is also where you can
start if you are already familiar with R and the {tidyverse}, but not
functional programming. If you are familiar with R but not the
{tidyverse} (or have no clue what the {tidyverse} is), then you can
start with Chapter 4. If you are familiar with R, the {tidyverse} and
functional programming, you might still be interested in this book,
especially Chapter 9 and 10, which deal with package development and
further advanced topics respectively.

<https://b-rodrigues.github.io/modern_R/>

## stats545 Data wrangling, exploration, and analysis with R

Jenny Bryan

Learn how to:

Explore, groom, visualize, and analyze data, make all of that
reproducible, reusable, and shareable, using R. This site is about
everything that comes up during data analysis except for statistical
modelling and inference.

<https://stat545.com/>

## What They Forgot to Teach You About R

Jennifer Bryan and Jim Hester

The initial impetus for creating these materials is a two-day hands-on
workshop. The target learner:

Has a moderate amount of R and RStudio experience.Is largely
self-taught.Suspects they have drifted into some idiosyncratic habits
that may slow them down or make their work products more brittle.Is
interested in (re)designing their R lifestyle, to be more effective and
more self-sufficient.

<https://rstats.wtf/>

## Field Guide to the R Ecosystem

Mark Sellors

This field guide aims to introduce the reader to the main components of
the R ecosystem that may be encountered in "the field".Whatever the
reason, whilst there is a wealth of in-depth information for people
actually using the language, I could find precious little information
that provided the sort of overview of the ecosystem that I know I'd have
appreciated when I first came to the language. And with that thought, a
field guide is born...

<https://fg2re.sellorm.com/>

## Functional Programming
Sara Altman, Bill Behrman, Hadley Wickham

This book is a practical introduction to functional programming using the tidyverse.

https://dcl-prog.stanford.edu/


## YaRrr! The Pirate's Guide to R

Nathaniel D. Phillips

Learn R from the ground up.

Let me make something very, very clear...

I did not write this book.

This whole story started in the Summer of 2015. I was taking a late
night swim on the Bodensee in Konstanz and saw a rusty object sticking
out of the water. Upon digging it out, I realized it was an ancient
usb-stick with the word YaRrr inscribed on the side. Intrigued, I
brought it home and plugged it into my laptop. Inside the stick, I found
a single pdf file written entirely in pirate-speak. After watching
several pirate movies, I learned enough pirate-speak to begin
translating the text to English. Sure enough, the book turned out to be
an introduction to R called The Pirate's Guide to R.

<https://bookdown.org/ndphillips/YaRrr/>

## Advanced R

[Hadley Whickham](https://twitter.com/hadleywickham)

This is the companion website for "Advanced R", a book in Chapman &
Hall's R Series. The book is designed primarily for R users who want to
improve their programming skills and understanding of the language. It
should also be useful for programmers coming to R from other languages,
as it explains some of R's quirks and shows how some parts that seem
horrible do have a positive side.

The book is free online. (Ignore the message redirecting you to the 2nd
edition, this is the latest edition)

<http://adv-r.had.co.nz/>

and the solutions can be found here:
<https://advanced-r-solutions.rbind.io/>

## Advanced R Solutions

Malte Grosser, Henning Bumann & Hadley Wickham

This book offers solutions to the exercises from Hadley Wickham's book
Advanced R (Edition 2). It is work in progress and under active
development. The 2nd edition of Advanced R has been published and we are
currently working towards completion.

<https://advanced-r-solutions.rbind.io/>

## Efficient R programming

[Colin Gillespie](http://www.mas.ncl.ac.uk/~ncsg3/) and [Robin
Lovelace](https://twitter.com/robinlovelace)

This book is for anyone who wants to make their R code faster to type,
faster to run and more scalable. These considerations generally come
after learning the very basics of R for data analysis.

The book is free online.

<https://csgillespie.github.io/efficientR/>

## The Tidyverse Cookbook

Edited by Garrett Grolemund

This book collects code recipes for doing data science with R's
tidyverse. Each recipe solves a single common task, with a minimum of
discussion.

<https://rstudio-education.github.io/tidyverse-cookbook/>

## The tidyverse style guide

[Hadley Whickham](https://twitter.com/hadleywickham)

Good coding style is like correct punctuation: you can manage without
it, butitsuremakesthingseasiertoread. This site describes the style used
throughout the tidyverse. It was derived from Google's original R Style
Guide - but Google's current guide is derived from the tidyverse style
guide.

<https://style.tidyverse.org/>

## Tidyverse design guide

Tidyverse team

The goal of this book is to help you write better R code. It has four
main components:

1.  Design problems which lead to suboptimal outcomes.

2.  Useful patterns that help solve common problems.

3.  Key principles that help you balance conflicting patterns.

4.  Selected case studies that help you see how all the pieces fit
    together with real code.

It is used by the tidyverse team to promote consistency across packages
in the core tidyverse.

<https://design.tidyverse.org/>

## Tidyverse Skills for Data Science

Carrie Wright, Shannon E. Ellis, Stephanie C. Hicks and Roger D. Peng

Book and Course formats

This course introduces a powerful set of data science tools known as the
Tidyverse. The Tidyverse has revolutionized the way in which data
scientists do almost every aspect of their job. We will cover the simple
idea of "tidy data" and how this idea serves to organize data for
analysis and modeling. We will also cover how non-tidy data can be
transformed to tidy data, the data science project life cycle, and the
ecosystem of Tidyverse R packages that can be used to execute a data
science project.

Book format <https://jhudatascience.org/tidyversecourse/>

Ebook: <https://leanpub.com/tidyverseskillsdatascience>

Course format
<https://www.coursera.org/specializations/tidyverse-data-science-r>

## Hands-On Programming with R

Garrett Grolemund

This book will teach you how to program in R, with hands-on examples. I
wrote it for non-programmers to provide a friendly introduction to the R
language. You'll learn how to load data, assemble and disassemble data
objects, navigate R's environment system, write your own functions, and
use all of R's programming tools. Throughout the book, you'll use your
newfound skills to solve practical data science problems.

<https://rstudio-education.github.io/hopr/>

## R for Excel users
Julie Lowndes & Allison Horst

This course is for Excel users who want to add or integrate R and RStudio into their existing data analysis toolkit. It is a friendly intro to becoming a modern R user, full of tidyverse, RMarkdown, GitHub, collaboration & reproducibility.

https://rstudio-conf-2020.github.io/r-for-excel/


## The R Language

[R Core team](https://stat.ethz.ch/R-manual/R-patched/doc/AUTHORS)

A collection of manuals: 1. An Introduction to R 1. The R Language
Definition 1. Writing R Extensions 1. R Installation and Administration
1. R Data Import/Export 1. R Internals

<https://stat.ethz.ch/R-manual/R-patched/doc/html/>


## R for Graduate Students
Y. Wendy Huynh

Hello! My name is Wendy Huynh and I am a current PhD student working in the behavioral neurosciences. I began my R journey at the end of my first year of graduate school, slowly and painfully piecing together code. Although programming was never really part of my program, I now see it as an integral part of my work.

Many fellow graduate students expressed interest in learning R, but didn’t know where to begin. Programming with R is still relatively niche among my cohort and there are very few formal classes teaching this subject.

Although there are many amazing guides/textbooks for R out there, very few of them featured examples relevant for my specific needs and were user-friendly enough for a true beginner. In the Fall of my second year, I began teaching a new graduate student in my lab everything I knew about R. However, I quickly found that teaching R – even just to one person – was very time consuming. I decided to write up assignments as a “short” guide to R. After writing a short 11 page “first assignment” and receiving positive feedback, I began writing up a second assignment. Then a third. Soon enough, I had written enough pages that I couldn’t deny that this “short guide” had turned into a book.

https://bookdown.org/yih_huynh/Guide-to-R-Book/


## R language for programmers

[John D Cook](https://www.johndcook.com/blog/services-2/)

I have written software professionally in perhaps a dozen programming
languages, and the hardest language for me to learn has been R. The
language is actually fairly simple, but it is unconventional. These
notes are intended to make the language easier to learn for someone used
to more commonly used languages such as C++, Java, Perl, etc.

<https://www.johndcook.com/blog/r_language_for_programmers/>

## R Cookbook - 2nd edition

JD Long, Paul Teetor

I have written software professionally in perhaps a dozen programming
languages, and the hardest language for me to learn has been R. The
language is actually fairly simple, but it is unconventional. These
notes are intended to make the language easier to learn for someone used
to more commonly used languages such as C++, Java, Perl, etc.

Not to be confused with Cookbook for R <https://rc2e.com/index.html>

## Cookbook for R

Winston Chang

The goal of the cookbook is to provide solutions to common tasks and
problems in analyzing data.

Not to be confused with R Cookbook <http://www.cookbook-r.com/>

## Tidy evaluation

Lionel Henry and Hadley Wickham

This guide is now superseded by more recent efforts at documenting tidy
evaluation in a user-friendly way. We now recommend reading:

The new Programming with dplyr vignette.

The Using ggplot2 in packages vignette.

(Oscar's note: I'm keeping this in for my own reference)

<https://tidyeval.tidyverse.org/>

## Rcpp for everyone

*Masaki E. Tsuda*

Rcpp is a package that enables you to implement R functions in C++. It
is easy to use even without deep knowledge of C++, because it is
implemented so as to write your C++ code in a style similar to R. And
Rcpp does not sacrifice execution speed for the ease of use, anyone can
get high performance outcome.

This document focuses on providing necessary information to users who
are not familiar with C++. Therefore, in some cases, I explain usage of
Rcpp conceptually rather than describing accurately from the viewpoint
of C++, so that I hope readers can easily understand it.

<https://teuder.github.io/rcpp4everyone_en/>

## The R Inferno

Patrick Burns

If R's behaviour has ever suprised you, then this book is a guide for
many more surprises, written in the style of Dante. It's a concise
report on number of common-errors and unexpected behaviours in R. This
book would make more sense, if you have been programming and are
familiar with such behaviours (not all though), as there is little time
spent on explaining why part of behaviour. As mentioned, it's a concise
book, 126 pages only.

<https://www.burns-stat.com/pages/Tutor/R_inferno.pdf>

## A sufficient Introduction to R

Derek l. Sonderegger

This book is intended to guide people that are completely new to
programming along a path towards a useful skill level using R. I belive
that while people can get by with just copying code chunks, that doesn't
give them the background information to modify the code in non-trivial
ways. Therefore we will spend more time on foundational details than a
"crash-course" would.

<https://dereksonderegger.github.io/570L/>

## Introduction to Programming with R

Reto Stauffer, Joanna Chimiak-Opoka, Thorsten Simon, Achim Zeileis

a learning resource for programming novices who want to learn
programming using the statistical programming language R. While one of
the major strengths of R is the broad variety of packages for statistics
and data science, this resource focuses on learning and understanding
basic programming concepts using base R. Only a couple of additional
packages are used and/or briefly discussed for special tasks.

This online book is specifically written for participants of the course
"Introduction to Programming: Programming in R" offered by the Digital
Science Center at Universität Innsbruck.

<https://eeecon.uibk.ac.at/~discdown/rprogramming/index.html>

## Mastering Software Development in R

[Roger D. Peng](https://twitter.com/rdpeng), [Sean
Kross](https://twitter.com/seankross), and [Brooke
Anderson](https://twitter.com/gbwanderson)

This book covers R software development for building data science tools.
This book provides rigorous training in the R language and covers modern
software development practices for building tools that are highly
reusable, modular, and suitable for use in a team-based environment or a
community of developers.

Pay what you want for the ebook, minimum \$0.00

<https://leanpub.com/msdr>

## Introduction to R - R spatial

R Spatial

This document provides a concise introduction to R. It emphasizes what
you need to know to be able to use the language in any context. There is
no fancy statistical analysis here. We just present the basics of the R
language itself. We do not assume that you have done any computer
programming before (but we do assume that you think it is about time you
did). Experienced R users obviously need not read this. But the material
may be useful if you want to refresh your memory, if you have not used R
much, or if you feel confused.

<https://rspatial.org/intr/index.html>

## Another Book on Data Science : Learn R and Python in Parallel

Nailong Zhang

There has been considerable debate over choosing R vs. Python for Data
Science. Based on my limited knowledge/experience, both R and Python are
great languages and are worth learning; so why not learn them together?

Besides the side-by-side comparison of the two popular languages used in
Data Science, this book also focuses on the translation from
mathematical models to codes. In the book, the audience could find the
applications/implementations of some important algorithms from scratch,
such as maximum likelihood estimation, inversion sampling, copula
simulation, simulated annealing, bootstrapping, linear regression
(lasso/ridge regression), logistic regression, gradient boosting trees,
etc.

<https://www.anotherbookondatascience.com/>

## Functional Programming in R

[Thomas Mailund](https://twitter.com/ThomasMailund)

Master functions and discover how to write functional programs in R. In
this concise book, you'll make your functions pure by avoiding
side-effects; you'll write functions that manipulate other functions,
and you'll construct complex functions using simpler functions as
building blocks.

<https://amzn.to/2wY4m11>

## Advanced Object-Oriented Programming in R

[Thomas Mailund](https://twitter.com/ThomasMailund)

Learn how to write object-oriented programs in R and how to construct
classes and class hierarchies in the three object-oriented systems
available in R. This book gives an introduction to object-oriented
programming in the R programming language and shows you how to use and
apply R in an object-oriented manner. You will then be able to use this
powerful programming style in your own statistical programming projects
to write flexible and extendable software.

Paid \~\$20

<https://amzn.to/2wZnBbp>

## Metaprogramming in R

[Thomas Mailund](https://twitter.com/ThomasMailund)

Learn how to manipulate functions and expressions to modify how the R
language interprets itself. This book is an introduction to
metaprogramming in the R language, so you will write programs to
manipulate other programs. Metaprogramming in R shows you how to treat
code as data that you can generate, analyze, or modify.

Paid \~\$20

<https://amzn.to/2x1cYUR>

## Functional Data Structures in R

[Thomas Mailund](https://twitter.com/ThomasMailund)

Get an introduction to functional data structures using R and write more
effective code and gain performance for your programs. This book teaches
you workarounds because data in functional languages is not mutable: for
example you'll learn how to change variable-value bindings by modifying
environments, which can be exploited to emulate pointers and implement
traditional data structures. You'll also see how, by abandoning
traditional data structures, you can manipulate structures by building
new versions rather than modifying them. You'll discover how these
so-called functional data structures are different from the traditional
data structures you might know, but are worth understanding to do
serious algorithmic programming in a functional language such as R.

Paid\~ \$20

<https://amzn.to/2oUG2cP>

## Domain-Specific Languages in R

[Thomas Mailund](https://twitter.com/ThomasMailund)

Gain an accelerated introduction to domain-specific languages in R,
including coverage of regular expressions. This compact, in-depth book
shows you how DSLs are programming languages specialized for a
particular purpose, as opposed to general purpose programming languages.
Along the way, you'll learn to specify tasks you want to do in a precise
way and achieve programming goals within a domain-specific context.

Domain-Specific Languages in R includes examples of DSLs including large
data sets or matrix multiplication; pattern matching DSLs for
application in computer vision; and DSLs for continuous time Markov
chains and their applications in data science. After reading and using
this book, you'll understand how to write DSLs in R and have skills you
can extrapolate to other programming languages.

Paid \~\$25

<https://amzn.to/2CDqhAU>

## An Introduction to R

[Alex Douglas](https://twitter.com/Scedacity), [Deon
Roos](https://twitter.com/DeonRoos88), [Ana
Couto](https://twitter.com/AnaSofiaCouto), [Francesca
Mancini](https://twitter.com/frances_mancini) and [David
Lusseau](https://twitter.com/lusseau)

The aim of this book is to introduce you to using R, a powerful and
flexible interactive environment for statistical computing and research.
R in itself is not difficult to learn, but as with learning any new
language (spoken or computer) the initial learning curve can be a little
steep and somewhat daunting. We have tried to simplify the content of
this book as much as possible and have based it on our own personal
experience of teaching (and learning) R over the last 15 years. It is
not intended to cover everything there is to know about R - that would
be an impossible task. Neither is it intended to be an introductory
statistics course, although you will be using some simple statistics to
highlight some of R's capabilities. The main aim of this book is to help
you climb the initial learning curve and provide you with the basic
skills and experience (and confidence!) to enable you to further your
experience in using R.

<https://intro2r.com/>

## An Introduction to Data Analysis

[Michael Franke](https://twitter.com/meanwhileina)

This book provides basic reading material for an introduction to data
analysis. It uses R to handle, plot and analyze data. After covering the
use of R for data wrangling and plotting, the book introduces key
concepts of data analysis from a Bayesian and a frequentist tradition.
This text is intended for use as a first introduction to statistics for
an audience with some affinity towards programming, but no prior
exposition to R.

<https://michael-franke.github.io/intro-data-analysis/index.html>

# Shiny

## A gRadual intRoduction to Shiny

Ted Laderas and Jessica Minnier

By the end of this workshop, you should be able to:

Browse examples in the shiny gallery and understand how they
work.Understand the components of a Shiny app and how they
communicate.Learn three basic design patterns to the shiny apps.

<https://laderast.github.io/gradual_shiny/>

## Mastering Shiny

Hadley Wickham

This book complements Shiny's online documentation and is intended to
help app authors develop a deeper understanding of Shiny. After reading
this book, you'll be able to write apps that have more customized UI,
more maintainable code, and better performance and scalability.

<https://mastering-shiny.org/>


## Mastering Shiny Solutions

[Maya Gans](http://maya.rbind.io/) and [Marly Gotti](https://www.marlygotti.com/)

This book offers solutions to the exercises from Hadley Wickham's book
[Mastering Shiny](https://mastering-shiny.org/). It is a work in
progress and under active development.

<https://mastering-shiny-solutions.org>


## Shiny Production with AWS Book

Business Science

A big problem exists... No one teaches Data Scientists how to deploy web
applications. You spend all of this time building Shiny web
applications. And then... [silence].

This book alongside the Shiny Developer with AWS Course (DS4B 202A-R)
solves this problem - teaching Data Scientists how to deploy, host, and
maintain web applications.

<https://business-science.github.io/shiny-production-with-aws-book/>

## Engineering Production-Grade Shiny Apps

Colin Fay, Sébastien Rochette, Vincent Guyader, Cervan Girard

This book will not get you started with Shiny, nor talk how to work with
Shiny once it is sent to production. What we'll see is the process of
building an application that will later be sent to production.

<https://engineering-shiny.org/>

## Supplement to Shiny in Production

This document is full of supplemental resources and content from the
[Shiny in Production
Workshop](https://rstudio.com/resources/rstudioconf-2019/shiny-in-production-principles-practices-and-tools/)
delievered at rstudio::conf 2019.

<https://kellobri.github.io/shiny-prod-book/>

## Outstanding User Interfaces with Shiny

David Granjon

This book will help you to:

Manipulate Shiny tags from R to create custom layouts. Harness the power
of CSS and JavaScript to quickly design apps standing out from the pack.
Discover the steps to import and convert existing web frameworks like
Bootstrap 4, framework7 and more Learn how Shiny internally deals with
inputs. Learn more about less documented Shiny mechanisms (websockets,
sessions, ...)

<https://divadnojnarg.github.io/outstanding-shiny-ui/>

## JavaScript for R

[John Coene](https://john-coene.com)

Learn how to build your own data visualsiation packages, improve shiny
with JavaScript, and use JavaScript for computations.

Freely avaiable online, paid print.

<https://javascript-for-r.com>

# Social Science

## Analyzing US Census Data: Methods, Maps, and Models in R
[Kyle Walker](https://twitter.com/kyle_e_walker)

Census data are widely used in the United States across numerous research and applied fields, including education, business, journalism, and many others. Until recently, the process of working with US Census data has required the use of a wide array of web interfaces and software platforms to prepare, map, and present data products. The goal of this book is to illustrate the utility of the R programming language for handling these tasks, allowing Census data users to manage their projects in a single computing environment.

https://walker-data.com/census-r/


## Computing for the Social Sciences

By [Dr. Benjamin Soltoff](https://bensoltoff.com/)

The goal of this course is to teach you basic computational skills and provide
you with the means to learn what you need to know for your own research. I
start from the perspective that you want to analyze data, and programming is a
means to that end. You will not become an expert programmer - that is a given.
But you will learn the basic skills and techniques necessary to conduct
computational social science, and gain the confidence necessary to learn new
techniques as you encounter them in your research.

We will cover many different topics in this course, including:

- Elementary programming techniques (e.g. loops, conditional statements,
  functions)
- Writing reusable, interpretable code
- Problem-solving - debugging programs for errors
- Obtaining, importing, and munging data from a variety of sources
- Performing statistical analysis
- Visualizing information
- Creating interactive reports
- Generating reproducible research

<https://cfss.uchicago.edu/notes/intro-to-course/>

## Crime by the Numbers: A Criminologist’s Guide to R
[Jacob Kaplan](https://twitter.com/JacobKaplanCrim)

This book introduces the programming language R and is meant for undergrads or graduate students studying criminology. R is a programming language that is well-suited to the type of work frequently done in criminology - taking messy data and turning it into useful information. While R is a useful tool for many fields of study, this book focuses on the skills criminologists should know and uses crime data for the example data sets.

https://crimebythenumbers.com/


## Introduction to R for Social Scientists:A Tidy Programming Approach
Ryan Kennedy, Philip Waggoner

Introduction to R for Social Scientists: A Tidy Programming Approach introduces the Tidy approach to programming in R for social science research to help quantitative researchers develop a modern technical toolbox. The Tidy approach is built around consistent syntax, common grammar, and stacked code, which contribute to clear, efficient programming. The authors include hundreds of lines of code to demonstrate a suite of techniques for developing and debugging an efficient social science research workflow. 

https://i2rss.weebly.com/#


## Public Policy Analytics: Code & Context for Data Science in Government
Ken Steif, Ph.D

The goal of this book is to make data science accessible to social scientists and City Planners, in particular. I hope to convince readers that one with strong domain expertise plus intermediate data skills can have a greater impact in government than the sharpest computer scientist who has never studied economics, sociology, public health, political science, criminology etc.

https://urbanspatial.github.io/PublicPolicyAnalytics/


## Social Data Science with R

Daniel Anderson, Brendan Cullen, Ouafaa Hmaddi

Here's an intro about why R is great and the cool things you can do with
it and new problems you can address.

<https://www.sds.pub/index.html>

## The Plain Person's Guide to Plain Text Social Science

Kieran Healy

As a beginning graduate student in the social sciences, what sort of
software should you use to do your work?1 More importantly, what
principles should guide your choices? I offer some general
considerations and specific answers.

<https://plain-text.co/index.html#introduction>

## Using R for Data Analysis in Social Sciences: A Research Project-Oriented Approach
Quan Li

This book seeks to teach undergraduate and graduate students in social sciences how to use R to manage, visualize, and analyze data in order to answer substantive questions and replicate published findings. This book distinguishes itself from other introductory R or statistics books in three ways. First, targeting an audience rarely exposed to statistical programming, it adopts a minimalist approach and covers only the most important functions and skills in R that one will need for conducting reproducible research projects. Second, it emphasizes meeting the practical needs of students using R in research projects. Specifically, it teaches students how to import, inspect, and manage data; understand the logic of statistical inference; visualize data and findings via histograms, boxplots, scatterplots, and diagnostic plots; and analyze data using one-sample t-test, difference-of-means test, covariance, correlation, ordinary least squares (OLS) regression, and model assumption diagnostics. Third, it teaches students how to replicate the findings in published journal articles and diagnose model assumption violations. 

Paid ~$40 and listing of library availability

https://www.worldcat.org/title/using-r-for-data-analysis-in-social-sciences-a-research-project-oriented-approach/oclc/1048009316

## Composite Indicator Development and Analysis in R with COINr

[William Becker](https://www.bluefoxdata.eu/)

*Composite indicators* are aggregations of indicators which aim to measure (usually socio-economic) complex and multidimensional concepts which are difficult to define, and cannot be measured directly. Examples include innovation, human development, environmental performance, and so on. This book gives a detailed guide on building composite indicators in R, focusing on the recent [COINr package](https://cran.r-project.org/package=COINr), which is an end-to-end development environment for composite indicators. Although COINr is the main tool used in the book, it also gives general explanation and guidance on composite indicator construction and analysis in R, ranging from normalisation, aggregation, multivariate analysis and global sensitivity analysis.

This book is free, open source and built in R using Bookdown.

<https://bluefoxr.github.io/COINrDoc/>

# Sport analytics

## Basketball Data Science with Applications in R

By Paola Zuccolotto, Marica Manisera

Using data from one season of NBA games, Basketball Data Science: With
Applications in R is the perfect book for anyone interested in learning
and applying data analytics in basketball. Whether assessing the spatial
performance of an NBA player's shots or doing an analysis of the impact
of high pressure game situations on the probability of scoring, this
book discusses a variety of case studies and hands-on examples using a
custom R package. The codes are supplied so readers can reproduce the
analyses themselves or create their own. Assuming a basic statistical
knowledge, Basketball Data Science with R is suitable for students,
technicians, coaches, data analysts and applied researchers.

paid \~\$35

<https://www.routledge.com/Basketball-Data-Science-With-Applications-in-R/Zuccolotto-Manisera/p/book/9781138600799>

## Exploring Baseball Data with R

Max Marchi, Jim Albert, Max Marchi, Jim Albert, Benjamin S. Baumer

This book introduces R to sabermetricians, baseball enthusiasts, and
students interested in exploring the richness of baseball data. It
equips you with the necessary skills and software tools to perform all
the analysis steps, from importing the data to transforming them into an
appropriate format to visualizing the data via graphs to performing a
statistical analysis.

Paid product \~\$50

<https://baseballwithr.wordpress.com/about/>

## Wrangling F1 Data With R: A Data Junkie's Guide

Tony Hirst

This book describes a range of data analysis and visualisation techniques that can be applied to motorsport timing and results data in general, and Formula One data in particular.

Paid product \$7.49+

https://leanpub.com/wranglingf1datawithr

## Visualising WRC Rally Stages With rayshader and R: A RallyDataJunkie Adventure

Tony Hirst

Taking a simple rally route dataset, what can we do with it? This book describes a wide range of techniques for working with geodata, including routes and elevantion rasters. From 2D and 3D mapping, to a wide range of route analysis techniques, the techniques described are also relevant to a wide range of othr route analysis contexts, including ecological trail analysis.

Free online book

https://rallydatajunkie.com/visualising-rally-stages/

## Visualising WRC Rally Timing and Results Data: A RallyDataJunkie Adventure

Tony Hirst

A handy guide to visualising a wide range of motorsport timing and results data, concentrating on rally data associated with the FIA World Rally Championship (WRC).

https://rallydatajunkie.com/visualising-wrc-rally-results/

## Coding for sports analytics: get started resources

Given the lack of sport-focussed R books, I've added this collection of
blog posts.

<https://brendankent.com/2020/09/15/coding-for-sports-analytics-resources-to-get-started/>

# Statistics

## Answering questions with data

Matthew J. Crump

This is a free textbook teaching introductory statistics for
undergraduates in Psychology. This textbook is part of a larger OER
course package for teaching undergraduate statistics in Psychology,
including this textbook, a lab manual, and a course website.

Looks like a comprehensive stats resource!

<https://crumplab.github.io/statistics/>

## Bayes rules!

-   Alicia A. Johnson, [Miles Ott](twitter.com/Miles_Ott), [Mine
    Dogucu](https://twitter.com/MineDogucu)

The primary goal of Bayes Rules! is to make modern Bayesian thinking,
modeling, and computing accessible to a broad audience. Bayes Rules!
empowers readers to weave Bayesian approaches into an everyday modern
practice of statistics and data science.\
The overall spirit is very applied: the book utilizes modern computing
resources and a reproducible pipeline; the discussion emphasizes
conceptual understanding; the material is motivated by data-driven
inquiry; and the delivery blends traditional "content" with "activity".

Free online book under construction but with 5 complete chapters on
2020/10/15

<https://www.bayesrulesbook.com/>

## Doing meta-analysis with R: A hands-on guide
Mathias Harrer, Pim Cuijpers, Toshi A. Furukawa, David D. Ebert 

This book serves as an accessible introduction into how meta-analyses can be conducted in R. Essential steps for meta-analysis are covered, including pooling of outcome measures, forest plots, heterogeneity diagnostics, subgroup analyses, meta-regression, methods to control for publication bias, risk of bias assessments and plotting tools.

Advanced, but highly relevant topics such as network meta-analysis, multi-/three-level meta-analyses, Bayesian meta-analysis approaches, SEM meta-analysis are also covered.

https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/


## Using R for Bayesian Spatial and Spatio-Temporal Health Modeling
By Andrew B. Lawson

Progressively more and more attention has been paid to how location affects health outcomes. The area of disease mapping focusses on these problems, and the Bayesian paradigm has a major role to play in the understanding of the complex interplay of context and individual predisposition in such studies of disease. Using R for Bayesian Spatial and Spatio-Temporal Health Modeling provides a major resource for those interested in applying Bayesian methodology in small area health data studies.

Paid ~$100
https://www.routledge.com/Using-R-for-Bayesian-Spatial-and-Spatio-Temporal-Health-Modeling/Lawson/p/book/9780367490126



## A Business Analyst's Introduction to Business Analytics: Intro to Bayesian Business Analytics in the R Ecosystem

[Adam Fleischhacker](https://twitter.com/preposterior)

This textbook goes farther than just showing you how to make
computational models using software or mathematical models using
statistics. It guides your thinking so you can align computational and
mathematical models with real-world scenarios. As you journey through
the material, you will feel empowered to effectively collaborate with
business stakeholders as you use modern software stacks and modern
statistical workflows to discover insight. R, RStudio, dplyr for data
manipulation, ggplot for data visualization, causact for graphical
models, and Bayesian data analysis feature prominently.

The full-color book (\$68) is available via Amazon:
<https://www.amazon.com/dp/B08DBYPRD2> and online (free) at:
<http://causact.com>. Video supplements for all chapters [available on
YouTube.](https://www.youtube.com/playlist?list=PLassxuIVwGLPy-mtohX-NXrjD8fc9FBOc)

## Common statistical tests are linear models: a work through

Steve Doogue

This is a reworking of the book Common statistical tests are linear
models (or: how to teach stats), written by Jonas Lindeløv. The book
beautifully demonstrates how many common statistical tests (such as the
t-test, ANOVA and chi-squared) are special cases of the linear model.
The book also demonstrates that many non-parametric tests, which are
needed when certain test assumptions do not hold, can be approximated by
linear models using the rank of values.

<https://steverxd.github.io/Stat_tests/>

## The Effect: An Introduction to Research Design and Causality
[Nick Huntington-Klein](https://twitter.com/nickchk)

The Effect is a book intended to introduce students (and non-students) to the concepts of research design and causality in the context of observational data. The book is written in an intuitive and approachable way and doesn’t overload on technical detail. Why teach regression and research design at the same time when they are fundamentally different things? First learn why you want to structure a design in a certain way, and what it is you want to do to the data, and then afterwards learn the technical details of how to run the appropriate model.

https://theeffectbook.net/


## Foundations of Statistics with R

Darrin Speegle and Bryan Clair

This book represents a fundamental rethinking of a calculus based first
course in probability and statistics. We offer a **breadth first**
approach, where the fundamentals of probability and statistics can be
taught in one semester. The statistical programming language R plays an
essential role throughout the text through simulations, data wrangling,
visualizations and statistical procedures. Data sets from a variety of
sources, including many from recent, open source scientific articles,
are used in examples and exercises. Demonstrations of important facts
are given through simulations, with some formal mathematical proofs as
well.

This book is an excellent choice for students studying data science,
statistics, engineering, computer science, mathematics, science,
business, or any field which requires the two semesters of calculus
needed to read this book.

<https://mathstat.slu.edu/~speegle/_book/preface.html>

## Handbook of Regression Modeling in People Analytics

[Keith McNulty](https://twitter.com/dr_keithmcnulty)

It is the author's firm belief that all people analytics professionals
should have a strong understanding of regression models and how to
implement and interpret them in practice, and the aim with this book is
to provide those who need it with help in getting there.

<http://peopleanalytics-regression-book.org/index.html>

## Learning statistics with R: A tutorial for psychology students and other beginners. (Version 0.6.1)

[Danielle Navarro](https://twitter.com/djnavarro)

Learning Statistics with R covers the contents of an introductory
statistics class, as typically taught to undergraduate psychology
students, focusing on the use of the R statistical software. The book
discusses how to get started in R as well as giving an introduction to
data manipulation and writing scripts. From a statistical perspective,
the book discusses descriptive statistics and graphing ﬁrst, followed by
chapters on probability theory, sampling and estimation, and null
hypothesis testing. After introducing the theory, the book covers the
analysis of contingency tables, t-tests, ANOVAs and regression. Bayesian
statistics are covered at the end of the book.

The book is free online.

<https://learningstatisticswithr-bookdown.netlify.app/>

## Mixed Models with R : Getting started with random effects

[Michael Clark](https://m-clark.github.io/)

Mixed models are an extremely useful modeling tool for situations in
which there is some dependency among observations in the data, where the
correlation typically arises from the observations being clustered in
some way.

<https://m-clark.github.io/mixed-models-with-R/>

## An Introduction to Statistical and Data Sciences via R

[Chester Ismay](https://twitter.com/old_man_chester) and [Albert
Kim](https://twitter.com/rudeboybert)

An incredibly beginner friendly introduction to both datascience and
statistics concepts as well as R.

The book is free to read online.

<https://moderndive.com/>

## An Introduction to Statistical Learning
Gareth James, Daniela Witten, Trevor Hastie, Rob Tibshirani

As the scale and scope of data collection continue to increase across virtually all fields, statistical learning has become a critical toolkit for anyone who wishes to understand data. An Introduction to Statistical Learning provides a broad and less technical treatment of key topics in statistical learning. Each chapter includes an R lab. This book is appropriate for anyone who wishes to use contemporary tools for data analysis. 

https://www.statlearning.com/



## ISLR tidymodels Labs
[Emil Hvitfeldt](https://twitter.com/Emil_Hvitfeldt)

This book aims to be a complement to the 1st version An Introduction to Statistical Learning book with translations of the labs into using the tidymodels set of packages.

The labs will be mirrored quite closely to stay true to the original material.

https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/index.html


## Statistical Rethinking

A Bayesian Course with Examples in R and Stan

Statistical Rethinking: A Bayesian Course with Examples in R and Stan
builds your knowledge of and confidence in making inferences from data.
Reflecting the need for scripting in today's model-based statistics, the
book pushes you to perform step-by-step calculations that are usually
automated. This unique computational approach ensures that you
understand enough of the details to make reasonable choices and
interpretations in your own modeling work.

<https://xcelab.net/rm/statistical-rethinking/>


## Statistical Rethinking with brms, ggplot2, and the tidyverse: Second edition

A Solomon Kurz

This ebook is based on the second edition of Richard McElreath’s (2020) 
text, Statistical rethinking: A Bayesian course with examples in R and Stan. 
My contributions show how to fit the models he covered with Paul Bürkner’s brms 
package, which makes it easy to fit Bayesian regression models in R using 
Hamiltonian Monte Carlo. I also prefer plotting and data wrangling with the packages 
from the tidyverse. So we’ll be using those methods, too.

<https://bookdown.org/content/4857/>

## OpenIntro Statistics

David Diez, [Mine Cetinkaya-Rundel](https://twitter.com/minebocek),
Christopher Barr, and [OpenIntro](https://twitter.com/OpenIntroOrg).

A complete foundation for Statistics, also serving as a foundation for
Data Science.

Leanpub revenue supports OpenIntro (US-based nonprofit) so we can
provide free desk copies to teachers interested in using OpenIntro
Statistics in the classroom and expand the project to support free
textbooks in other subjects.

More resources: [openintro.org](https://www.openintro.org/).

Pay what you want for the ebook, minimum \$0.00, however if you are able
to, please consider the cause above. Thanks!

<https://leanpub.com/openintro-statistics>

## One Way ANOVA with R: Completely Randomized Design - Between Groups
Bruce Dudek

This document can be a standalone “how-to” document for R users. However, it
is primarily intended for students in the APSY510/511 statistics sequence at the
University at Albany. It is a fairly thorough treatment of graphical and inferential evaluation of one-factor designs. It presumes prior background coverage
of the ANOVA logic from standard textbooks such as Howell or Maxwell, Delaney and Kelley (2017). The analyses are intended to parallel and exhaust the
methods already covered with SPSS, and to extend them to additional topics.

https://bcdudek.net/anova/oneway_anova_basics.pdf


## Introduction to Modern Statistics

[Mine Çetinkaya-Rundel](https://twitter.com/minebocek), [Johanna
Hardin](@jo_hardin47)

We hope readers will take away three ideas from this book in addition to
forming a foundation of statistical thinking and methods.

1.  Statistics is an applied field with a wide range of practical
    applications.
2.  You don't have to be a math guru to learn from interesting, real
    data.
3.  Data are messy, and statistical tools are imperfect. However, when
    you understand the strengths and weaknesses of these tools, you can
    use them to learn interesting things about the\~world.

<https://openintro-ims.netlify.app/>

## Statistical inference for data science

Brian Caffo

This book gives a brief, but rigorous, treatment of statistical
inference intended for practicing Data Scientists.

Pay what you want for the ebook, minimum \$0.00

<https://leanpub.com/LittleInferenceBook>

## Statistics (The Easier Way) With R, 3rd. Ed. (TIDYVERSION)

[Nicole Radziwill](https://radziwill.cc)

This introductory applied statistics handbook shows you how to run tests
analytically, and then how to run exactly the same steps using R. No
steps are skipped, making this particularly well suited for beginners or
people who need a quick lookup. Used at 30+ universities around the
globe.

<https://amzn.to/3b9ha8s> - varies between \$37-43 & you can request
free PDF after your order
<https://www.e-junkie.com/ecom/gb.php?&c=single&cl=147256&i=1614407> -
\$25 for PDF only

## End-to-End Solved Problems With R: a catalog of 26 examples using statistical inference

[Nicole Radziwill](https://radziwill.cc)

Lots of worked problems, analytically and in R! Useful supplement for an
introductory applied stats class.

<https://amzn.to/2EREAn2> - used for \$4-18, new \$19-20
<https://www.e-junkie.com/ecom/gb.php?c=single&cl=147256&i=1548704> -
\$10 for PDF only

## Statistics and Data with R: An Applied Approach Through Examples

Yosef Cohen and Jeremiah Y. Cohen

R, an Open Source software, has become the de facto statistical
computing environment. It has an excellent collection of data
manipulation and graphics capabilities. It is extensible and comes with
a large number of packages that allow statistical analysis at all levels
-- from simple to advanced -- and in numerous fields including Medicine,
Genetics, Biology, Environmental Sciences, Geology, Social Sciences and
much more. The software is maintained and developed by academicians and
professionals and as such, is continuously evolving and up to date.
Statistics and Data with R presents an accessible guide to data
manipulations, statistical analysis and graphics using R.

The E-Book costs \$97.00 while the print version costs \$121.75

<https://www.wiley.com/en-us/Statistics+and+Data+with+R%3A+An+Applied+Approach+Through+Examples-p-9780470758052>

## TEACUPS, GIRAFFES, & STATISTICS

HASSE WALUM, [DESIRÉE DE LEON](https://twitter.com/dcossyle)

A delightful series of beautifully illustrated modules to learn
statistics and R coding for students, scientists, and stats-enthusiasts.

<https://tinystats.github.io/teacups-giraffes-and-statistics/index.html>

## Modern Statistics with R

[Måns Thulin](https://twitter.com/mansthulin)

This book covers the fundamentals of data science and statistics. The
first half deals with the basics of R and R coding, data wrangling,
exploratory data analysis and more advandced programming. The second
half deals with modern statistics (favouring permutation tests, the
bootstrap and Bayesian methods over traditional asymptotic methods),
regression models and predictive modelling. It also contains information
about debugging and explanations of 25 commonly encountered error
messages in R. In addition, there are 170 or so exercises with fully
worked solutions.

<http://www.modernstatisticswithr.com/>

## Foundations of Statistics with R 
[Darrin Speegle](https://twitter.com/speegled)

This book represents a fundamental rethinking of a calculus based first
course in probability and statistics. We offer a breadth first approach,
where the fundamentals of probability and statistics can be taught in
one semester.1 The statistical programming language R plays an essential
role throughout the text through simulations, data wrangling,
visualizations and statistical procedures. Data sets from a variety of
sources, including many from recent, open source scientific articles,
are used in examples and exercises. Demonstrations of important facts
are given through simulations, with some formal mathematical proofs as
well.

<https://mathstat.slu.edu/~speegle/_book/preface.html>

## Statistical Thinking in the 21st Century

[Russell Poldrack](https://github.com/poldrack)

This textbook aims to cover modern methods that take advantage of today's
increased computing power, while also balancing the accessibility of the
material for students not wanting to wade through a lot of story to get to the
statistical knowledge while reading Andy Field's graphic novel statistics
books, "An Adventure in Statistics".

The main site below has companion sites in R and Python:

- R companion <https://statsthinking21.github.io/statsthinking21-R-site/>
- Python companion <https://statsthinking21.github.io/statsthinking21-python/>

<https://statsthinking21.github.io/statsthinking21-core-site/>

# Time Series Analysis and Forecasting

## Forecasting: Principles and Practice

Rob J Hyndman and George Athanasopoulos

This textbook is intended to provide a comprehensive introduction to
forecasting methods and to present enough information about each method
for readers to be able to use them sensibly.

The book is written for three audiences: (1) people finding themselves
doing forecasting in business when they may not have had any formal
training in the area; (2) undergraduate students studying business; (3)
MBA students doing a forecasting elective.

Second edition supporting the
[forecast](https://pkg.robjhyndman.com/forecast/) package:
<https://otexts.com/fpp2/>

Third edition supporting the [fable](https://fable.tidyverts.org/)
package: <https://otexts.com/fpp3/>

## Time Series Analysis and Its Applications

Robert H. Shumway and David S. Stoffer

The book is designed as a textbook for graduate level students in the
physical, biological, and social sciences and as a graduate level text
in statistics. Some parts may also serve as an undergraduate
introductory course. Theory and methodology are separated to allow
presentations on different levels. In addition to coverage of classical
methods of time series regression, ARIMA models, spectral analysis and
state-space models, the text includes modern developments including
categorical time series analysis, multivariate spectral methods, long
memory series, nonlinear models, resampling techniques, GARCH models,
ARMAX models, stochastic volatility, wavelets, and Markov chain Monte
Carlo integration methods.

<https://www.stat.pitt.edu/stoffer/tsa4/index.html>

## Hands-On Time Series Analysis with R

Rami Krispin

The book provides an introduction for time series analysis with R. It
covers the general workflow of time series analysis - working and
handling time series data, descriptive analysis, predictive analysis,
modeling strategies, etc.

This book is designed for data scientists who wish to learn time series
analysis and forecasting or data analysts who use Excel-based
forecasting methods and wish to use more robust methods.

Paid \~\$30

<https://www.packtpub.com/product/hands-on-time-series-analysis-with-r/9781788629157>

## Practical Time Series Forecasting with R: A Hands-On Guide

Galit Shmueli and Kenneth C. Lichtendahl, Jr

Practical Time Series Forecasting with R provides an applied approach to
time-series forecasting. Forecasting is an essential component of
predictive analytics.

Balancing theory and practice, the books introduce popular forecasting
methods and approaches used in a variety of business applications, and
are ideal for Business Analytics, MBA, Executive MBA, and Data Analytics
programs in business schools.

Paid \~\$30

<http://www.forecastingbook.com/>

## Time Series - A Data Analysis Approach Using R

Robert H. Shumway and David S. Stoffer

The goals of this text are to develop the skills and an appreciation for
the richness and versatility of modern time series analysis as a tool
for analyzing dependent data. A useful feature of the presentation is
the inclusion of nontrivial data sets illustrating the richness of
potential applications to problems in the biological, physical, and
social sciences as well as medicine. The text presents a balanced and
comprehensive treatment of both time and frequency domain methods with
an emphasis on data analysis.

Paid \~\$40

<https://www.routledge.com/Time-Series-A-Data-Analysis-Approach-Using-R/Shumway-Stoffer/p/book/9780367221096>

## Applied Time Series Analysis for Fisheries and Environmental Sciences

E. E. Holmes, M. D. Scheuerell, and E. J. Ward

This is material that was developed as part of a course we teach at the
University of Washington on applied time series analysis for fisheries
and environmental data.

<https://nwfsc-timeseries.github.io/atsa-labs/>

## Fisheries Catch Forecasting

Elizabeth Holmes

The focus of this book is on analysis of univariate time series. However
multivariate regression with autocorrelated errors and multivariate
autoregressive models (MAR) will be covered more briefly. For an indepth
discussion of multivariate autoregressive models and multivariate
autoregressive state-space models, see Holmes, Ward and Scheuerell
(2018).

<https://fish-forecast.github.io/Fish-Forecast-Bookdown/index.html>

# Teaching

## Data Science in a Box

[Mine Çetinkaya-Rundel](https://twitter.com/minebocek)

This book focuses on how to efficiently teach data science to students
with little to no background in computing and statistical thinking. The
core content of the course focuses on data acquisition and wrangling,
exploratory data analysis, data visualization, inference, modelling, and
effective communication of results.

This book is free online.

<https://datasciencebox.org/>

## rstudio4edu

[Desirée De Leon](https://desiree.rbind.io/) and [Alison
Hill](https://alison.rbind.io/)

> A Handbook for Teaching and Learning with R and RStudio

A book for educators in the data science space who wish to create
educational materials that are engaging for students and inspiring to
other educators. This book is a cookbook for generating materials for

-   R Markdown lessons
-   R packages
-   R Markdown websites
-   Distill sites
-   Bookdown books
-   Blogdown sites

<https://rstudio4edu.github.io/rstudio4edu-book/>

## Teaching Tech Together

Greg Wilson

Not an R book per se, but comes highly recommended about how to teach
programming.

Grassroots groups have sprung up around the world to teach programming,
web design, robotics, and other skills to free-range learners. These
groups exist so that people don't have to learn these things on their
own, but ironically, their founders and teachers are often teaching
themselves how to teach.

There's a better way. Just as knowing a few basic facts about germs and
nutrition can help you stay healthy, knowing a few things about
cognitive psychology, instructional design, inclusivity, and community
organization can help you be a more effective teacher. This book
presents key ideas you can use right now, explains why we believe they
are true, and points you at other resources that will help you go
further

<http://teachtogether.tech/en/index.html>

## What they forgot to teach you about teaching R

[Desiree de Leon](https://desiree.rbind.io/)

This book is offered at rstudio::global(2021), as part of the Diversity
Scholars program.

In this workshop, you will learn about using the RStudio IDE to its full
potential for teaching R. Whether you're an educator by profession, or
you do education as part of collaborations or outreach, or you want to
improve your workflow for giving talks, demos, and workshops, there is
something for you in this workshop. During the workshop we will cover
live coding best practices, tips for using RStudio Cloud for teaching
and building learnr tutorials, and R Markdown based tools for developing
instructor and student facing teaching materials.

<https://wtf-teach.netlify.app/>

# Text analysis

## Text Mining with R

[Julia Silge](https://twitter.com/juliasilge) and [David
Robinson](https://twitter.com/drob)

This book serves as an introduction of text mining using the tidytext
package and other tidy tools in R. The functions provided by the
tidytext package are relatively simple; what is important are the
possible applications. Thus, this book provides compelling examples of
real text mining problems.

<https://www.tidytextmining.com/>

## Supervised Machine Learning for Text Analysis in R

[Emil Hvitfeldt](https://twitter.com/Emil_Hvitfeldt), [Julia
Silge](https://twitter.com/juliasilge)

Modeling as a statistical practice can encompass a wide variety of
activities. This book focuses on supervised or predictive modeling for
text, using text data to make predictions about the world around us. We
use the tidymodels framework for modeling, a consistent and flexible
collection of R packages developed to encourage good statistical
practice.

<https://smltar.com/>

## Text Mining With Tidy Data Principles

[Julia Silge](https://twitter.com/juliasilge)

Text data sets are diverse and ubiquitous, and tidy data principles
provide an approach to make text mining easier, more effective, and
consistent with tools already in wide use. In this tutorial, you will
develop your text mining skills using the tidytext package in R, along
with other tidyverse tools.

<https://juliasilge.shinyapps.io/learntidytext/>

# Version control

## Happy Git and GitHub for the useR

Jenny Bryan, the STAT 545 TAs, Jim Hester

Happy Git provides opinionated instructions on how to:

Install Git and get it working smoothly with GitHub, in the shell and in
the RStudio IDE. Develop a few key workflows that cover your most common
tasks.Integrate Git and GitHub into your daily work with R and R
Markdown.

The target reader is someone who uses R for data analysis or who works
on R packages, although some of the content may be useful to those
working in adjacent areas.

<https://happygitwithr.com/>

## Github actions with R

Chris Brown, Murray Cadzow, Paula A Martinez, Rhydwyn McGuire, David
Neuzerling, David Wilkinson, Saras Windecker

GitHub actions allow us to trigger automated steps after we launch
GitHub interactions such as when we push, pull, submit a pull request,
or write an issue.

<https://ropenscilabs.github.io/actions_sandbox/>

## Github learning lab

Not R specific or even a book, but looks like a good resource to learn
git.

<https://lab.github.com/>

## The Beginner's Guide to Git and GitHub

Thomas Mailund

A quick beginner's guide to using Git and GitHub.You have heard about
git and GitHub and want to know what the buzz is about. That is what I
am here to tell you. Or, at least, I am here to give you a quick
overview of what you can do with git and GitHub. I won't be able, in the
space here, to give you an exhaustive list of features---in all honesty,
I don't know enough myself to be able to claim expertise with these
tools. I am only a frequent user, but I can get you started and give you
some pointers for where to learn more. That is what this booklet is for.

Paid \~\$5

<https://amzn.to/2Nt0rDY>

## Git and Github for Advanced Ecological Data Analysis

Alexa Fredston

This material was prepared for a three-hour virtual session to teach Git
and Github to a graduate-level course on Advanced Ecological Data
Analysis taught at Rutgers University by Malin Pinsky and Rachael
Winfree. (However, the only course-specific material is Section 4; the
rest should be applicable to any reader.)

<https://afredston.github.io/learn-git/learn-git.html>

# Workflow

## Agile Data Science with R

Edwin Thoen

I joined a Scrum team (frontend, backend, ux designer, product owner,
second data scientist) to create a machine learning model that we
brought to production using the Agile principles. It was an inspiring
experience from which I learned a great deal. My colleagues patiently
explained the principles of Agile software development and together we
applied them to the data science context.All these experiences
culminated in the workflow that we now adhere to at work and I think it
is worthwhile to share it. It is heavily based on the principles of
Agile software production, hence the title. We have explored which of
the concepts from Agile did and did not work for data science and we got
hands-on experience in working from these principles in an R project
that actually got to production.

<https://edwinth.github.io/ADSwR/>

## The Data Validation Cookbook

[Mark P.J. van der Loo](https://twitter.com/markvdLoo)

The purposes of this book include demonstrating the main tools and
workflows of the validate package, giving examples of common data
validation tasks, and showing how to analyze data validation results.

<https://data-cleaning.github.io/validate/>

## How I Use R

David Keyes // R for the Rest of Us

There are many great learning resources at the beginner stage and some
incredible tutorials to master complex tasks in R. But, drawing from a
concept in urban planning, there are far fewer resources in the middle.

Stretching the metaphor perhaps to its breaking point, new R users at
the "detached single-family home" stage can't get to the advanced
"mid-rise" level without going through the middle stage. The "missing
middle" in the R neighborhood is the lack of resources to that answer
the types of nuts and bolts questions that new R users often have.
Things like:

How should I organize my file structure when creating a new project?
Should I do data cleaning in an RMarkdown file or an R script file? How
do I find packages? How do I know if the packages I find are high
quality?

This book is my attempt to provide answers to these types of questions.

<https://howiuser.com/>

## Github actions with R

Chris Brown, Murray Cadzow, Paula A Martinez, Rhydwyn McGuire, David
Neuzerling, David Wilkinson, Saras Windecker

GitHub actions allow us to trigger automated steps after we launch
GitHub interactions such as when we push, pull, submit a pull request,
or write an issue.

<https://ropenscilabs.github.io/actions_sandbox/>

## The targets R Package User Manual

Will Landau

The targets package is a Make-like pipeline toolkit for Statistics and
data science in R. With targets, you can maintain a reproducible
workflow without repeating yourself. targets learns how your pipeline
fits together, skips costly runtime for tasks that are already up to
date, runs only the necessary computation, supports implicit parallel
computing, abstracts files as R objects, and shows tangible evidence
that the results match the underlying code and data.

This manual is a step-by-step written guide to targets

<https://wlandau.github.io/targets-manual/index.html>

# Other compendiums

## Awesome network analysis

A compendium of resources that look really valuable. 

https://github.com/briatte/awesome-network-analysis


## Bookdown archive

An archive all books published via bookdown.org. It's a very very big
repo.

<https://bookdown.org/home/archive/>

## R project book compendium

A searchable archive of 180+ books.

https://www.r-project.org/doc/bib/R-jabref.html


## Use R! Springer series

This is a collection of some 70+ books. This series of inexpensive and
focused books on R will publish shorter books aimed at practitioners.
Books can discuss the use of R in a particular subject area (e.g.,
epidemiology, econometrics, psychometrics) or as it relates to
statistical topics (e.g., missing data, longitudinal data).

All are paid products

<https://www.springer.com/series/6991?detailsPage=titles>

## Data Science with R: A Resource Compendium

Martin Monkman

This book grew out of my evergrowing collection of reference materials
that was saved as an expanding array of markdown files in a github repo.
By assembling it as a book, I hope that it will be more accessible and
useful to other R users.

<https://bookdown.org/martin_monkman/DataScienceResources_book/>

## R on the web

[Guillaume Coqueret](https://twitter.com/g_coqueret)

Useful links for people interested in R.

<https://github.com/shokru/rstats/blob/master/material/R_links.md>

## CRAN doc collections

Note these projects are frozen, but they do contain a lot of resources
in multiple languages.

Many of these are quite old publications, but it doesn't mean they're
outdated or not useful. If you're really digging for a specific resource
that you can't find anywhere else, it may be here. Good luck!

<https://cran.r-project.org/other-docs.html>

<https://www.r-project.org/doc/bib/R-books.html>
