---
title: "Big Book of R"
author: "Oscar Baruffa"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::gitbook:
    includes:
      in_header: [google-analytics.html]
    config:
      edit: https://github.com/oscarbaruffa/BigBookofR/edit/master/%s
      toc:
        before: |  
          <br/><center><b><a href="./index.html">&nbsp&nbspBig Book of R</a></b></center></li>
        after: |
          <li><center><a href="https://bookdown.org/yihui/bookdown/">
          Published with bookdown</a></center></li>
site: bookdown::bookdown_site
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(metathis)
meta() %>%
  meta_description(
    "100+ Free R programming books"
  ) %>% 
  meta_name("github-repo" = "oscarbaruffa/BigBookofR") %>% 
  meta_viewport() %>% 
  meta_social(
    title = "Big Book of R",
    url = "https://www.bigbookofr.com/",
    image = "https://github.com/oscarbaruffa/BigBookofR/blob/master/images/big_book_social.png",
    image_alt = "The cover of the Big Book of R book",
    og_type = "book",
    og_author = "Oscar Baruffa",
    twitter_card_type = "summary",
    twitter_creator = "@oscarbaruffa"
  )
```


# Welcome :)

## Your last-ever bookmark
Thanks for stopping by. If you're like me, you can't help but bookmark every R-related programming book you find in the hopes that one day you, or someone you know, might find it useful.


I've been collecting these for about 2 years now, totaling about 100 books, and thought I'd share it with you :).

Hopefully this is the only bookmark you'll need in future ;).

Most of these are free, some are paid (most are very affordable).


## Searching

If there's something specific you're looking for, use the menu or search using the magnifying glass icon at the top of the screen.


## Contributing

Please feel free to contribute paid and free books - see the  [github.](https://github.com/oscarbaruffa/BigBookofR)


## Contributors

If you've contributed, add your name and twitter / blog link below!

[Oscar Baruffa](https://twitter.com/OscarBaruffa)

Mohit Sharma

[Vebash Naidoo](https://twitter.com/Sciencificity)

[Julia Silge](https://twitter.com/juliasilge)

[Erik Gahner Larsen](https://twitter.com/erikgahner)

[Nicole Radziwill](https://radziwill.cc)

[Nistara Randhawa](https://twitter.com/nistara_r)

[Antoine Fabri](https://twitter.com/antoine_fabri)

[Jon Calder](https://twitter.com/jonmcalder)

[Mike Smith](https://twitter.com/grimbough)

[Ben Bolker](https://github.com/bbolker)

[Maëlle Salmon](https://twitter.com/ma_salmon)

[Laura Ellis](https://twitter.com/LittleMissData)

[Bryan Shalloway](https://twitter.com/brshallo)

[Antonio Uzal](https://twitter.com/antonio_uzal)

[Louis Aslett](http://www.louisaslett.com/)

[Lluís Revilla Sancho](https:llrs.dev)

[Brendan Cullen](https://twitter.com/_bcullen)

## Licence

This website/book is free to use, and is licensed under the [Creative Commons Attribution-NonCommercial-NoDerivs 3.0 License](https://creativecommons.org/licenses/by-nc-nd/3.0/us/){target="blank}.


## About me

I'm Oscar. Fairly new to R and loving it. If you like this book, feel free to say "Hi!" on [Twitter](https://twitter.com/OscarBaruffa). 
