# Geospatial

## A Crash Course in Geographic Information Systems (GIS) using R

- Michael Branion-Calles

Introduction into concepts for GIS and spatial data in R. Later chapters are not finished.

Link: [https://bookdown.org/michael_bcalles/gis-crash-course-in-r/](https://bookdown.org/michael_bcalles/gis-crash-course-in-r/)

## An Introduction to Spatial Data Analysis and Statistics: A Course in R

- Antonio Paez

The objective of this book is to introduce selected topics in applied spatial statistics. My aim with this book is to introduce key concepts and techniques in the
 statistical analysis of spatial data in an intuitive way. While there are other resources that offer more advanced treatments of every single 
one of these topics, this book should be appealing to undergraduate students or others who are approaching the topic for the first time.

Link: [https://paezha.github.io/spatial-analysis-r/](https://paezha.github.io/spatial-analysis-r/)

## Applied Microeconometrics

- Paula Moraga

The book combines theory and practice using real-world data science examples such as disease risk mapping, air pollution prediction, species distribution modeling, crime mapping, and real state analyses.

Link: [https://www.paulamoraga.com/book-spatial/index.html](https://www.paulamoraga.com/book-spatial/index.html)

## Geocomputation with R

- Robin Lovelace
- Jakub Nowosad
- Jannes Muenchow

This is the online home of Geocomputation with R, a book on geographic
data analysis, visualization and modeling.

Link: [https://geocompr.robinlovelace.net/](https://geocompr.robinlovelace.net/)

## Geospatial Health Data Modeling and Visualization with R-INLA and Shiny

- Paula Moraga

This book describes spatial and spatio-temporal statistical methods and
visualization techniques to analyze georeferenced health data in R.
After a detailed introduction of geospatial data, the book shows how to
develop Bayesian hierarchical models for disease mapping and apply
computational approaches such as the integrated nested Laplace
approximation (INLA) and the stochastic partial differential equation
(SPDE) to analyze areal and geostatistical data.

Link: [https://www.paulamoraga.com/book-geospatial/](https://www.paulamoraga.com/book-geospatial/)

## Intro to GIS and Spatial Analysis

- Manuel Gimond

A well structures book which serves as an introduction to GIS and spatial data analysis. The book is structures around the authors Introduction to GIS and Spatial Analysis course (ES214). The book provides a good introduction to working with geographical datasets and performing spatial analysis such as point pattern analysis, hypothesis testing, spatial autocorrelation and spatial interpolation,

Link: [https://mgimond.github.io/Spatial/index.html](https://mgimond.github.io/Spatial/index.html)

## Introduction to Spatial Data Programming with R

- [Michael Dorman](https://twitter.com/MichaelDorman84)

This book introduces processing and analysis methods for working with
spatial data in R. The book is composed of two parts. The *first* part
gives an overview of the basic syntax and usage of the R language,
required before we can start working with spatial data. The *second*
part then covers spatial data workflows, including how to process
rasters, vector layers, and both of them together, as well as two
selected advanced topics: spatio-temporal data and spatial
interpolation.

Link: [https://geobgu.xyz/r](https://geobgu.xyz/r)

## Introduction to urban accessibility

- Rafael H. M. Pereira
- Daniel Herszenhut

The aim of this book is to equip its readers with the fundamental concepts, the data analysis skills and the processing tools needed to perform urban accessibility analyses and transportation projects impact assessments. The book was written with the problems faced by public managers, policy makers, students and researchers working on urban and transportation planning in mind. Hence, the book is essentially practical. All the material in the book is presented with reproducible examples using open data sets and the R programming language.

Link: [https://ipeagit.github.io/intro_access_book/](https://ipeagit.github.io/intro_access_book/)

## Predictive Soil Mapping with R

- [Tom Heng](https://opengeohub.org/people/tom-hengl)
- [Robert A. MacMillan](https://opengeohub.org/people/bob-macmillan)

Predictive Soil Mapping (PSM) with R explains how to import, process and
analyze soil data in R using the state-of-the-art soil and Machine
Learning packages with ultimate objective to produce most objective
spatial predictions of soil numeric and factor-type variables. Especial
focus has been put on using R in combination with the Open Source GIS
such as GDAL, SAGA GIS and similar, and on using Machine Learning
packages ranger, xgboost, SuperLearner and similar. This book is
licensed under a Creative Commons Attribution-ShareAlike 4.0
International License. Contributions of new chapters are welcome.

Link: [https://soilmapper.org](https://soilmapper.org)

## R for Geographic Data Science

- [Stefano De Sabbata](https://twitter.com/maps4thought)

The materials aim to cover the necessary skills in basic programming, data wrangling and reproducible research to tackle sophisticated but non-spatial data analyses. The first part of the module will focus on core programming techniques, data wrangling and practices for reproducible research. The second part of the module will focus on non-spatial data analysis approaches, including statistical analysis and machine learning.

Link: [https://sdesabbata.github.io/r-for-geographic-data-science/index.html](https://sdesabbata.github.io/r-for-geographic-data-science/index.html)

## Spatial Data Science With applications in R

- Edzer Pebesma
- Roger Bivand

This book introduces and explains the concepts underlying spatial data:
points, lines, polygons, rasters, coverages, geometry attributes, data
cubes, reference systems, as well as higher-level concepts including how
attributes relate to geometries and how this affects analysis.

Link: [https://r-spatial.org/book/](https://r-spatial.org/book/)

## Spatial Data Science with R

- [RSpatial](https://github.com/rspatial)

This website provides materials to learn about spatial data analysis and modeling with R. R is a widely used programming language and software environment for data science. R has advanced capabilities for managing spatial data; and it provides unparalleled opportunities for analyzing such data.

Link: [https://rspatial.org/raster/index.html#](https://rspatial.org/raster/index.html#)

## Spatial Microsimulation with R

- [Robin Lovelace](https://www.robinlovelace.net/)
- [Morgane Dumont](https://directory.unamur.be/staff/modumont)

Imagine a world in which data on companies, households and governments were widely available. Imagine, further, that researchers and decision-makers acting in the public interest had tools enabling them to test and model such data to explore different scenarios of the future. People would be able to make more informed decisions, based on the best available evidence. In this technocratic dreamland pressing problems such as climate change, inequality and poor human health could be solved.

These are the types of real-world issues that we hope the methods in this book will help to address. Spatial microsimulation can provide new insights into complex problems and, ultimately, lead to better decision-making. By shedding new light on existing information, the methods can help shift decision-making processes away from ideological bias and towards evidence-based policy.

Link: [https://spatial-microsim-book.robinlovelace.net/index.html](https://spatial-microsim-book.robinlovelace.net/index.html)

## Spatial Modelling for Data Scientists

- Francisco Rowe
- Dani Arribas-Bel

This is the website for “Spatial Modeling for Data Scientists”. This is a course taught by Dr. Francisco Rowe and Dr. Dani Arribas-Bel in the Second Semester of 2020/21 at the University of Liverpool, United Kingdom. You will learn how to analyse and model different types of spatial data as well as gaining an understanding of the various challenges arising from manipulating such data.

Link: [https://gdsl-ul.github.io/san/](https://gdsl-ul.github.io/san/)

## Spatial Statistics for Data Science: Theory and Practice with R

- Paula Moraga

The book combines theory and practice using real-world data science examples such as disease risk mapping, air pollution prediction, species distribution modeling, crime mapping, and real state analyses.

Link: [https://www.paulamoraga.com/book-spatial/index.html](https://www.paulamoraga.com/book-spatial/index.html)

## Spatial sampling with R

- Dick J. Brus

This book describes and illustrates classical, basic sampling designs for a spatial survey, as well as more recently developed, advanced sampling designs and estimators. Part I of the book is about random sampling designs for estimating a mean, total, or proportion of a population or of several subpopulations. Part II focuses on sampling designs for mapping.

Link: [https://dickbrus.github.io/SpatialSamplingwithR/](https://dickbrus.github.io/SpatialSamplingwithR/)

## Using R for Digital Soil Mapping

- Malone, Brendan P.
- Minasny, Budiman
- McBratney, Alex B

Describes in detail, with ample exercises, how digital soil mapping is
done This work includes a number of work-flows that direct users how to
create digital soil maps for their own projects This work includes
tutorials for users to learn the fundamentals of R, but with a focus on
how to use it for digital soil mapping

Link: [https://www.springer.com/gp/book/9783319443256](https://www.springer.com/gp/book/9783319443256)

## sits: Data Analysis and Machine Learning on Earth Observation Data Cubes with Satellite Image Time Series

- Gilberto Camara
- Rolf Simoes
- Felipe Souza
- Alber Sanchez
- Lorena Santos
- et al

Using time series derived from big Earth Observation data sets is one of the leading research trends in Land Use Science and Remote Sensing. One of the more promising uses of satellite time series is its application to classify land use and land cover. Information on land is critical for sustainable development because our growing demand for natural resources is causing significant environmental impacts. The target audience for sits is the new generation of specialists who understand the principles of remote sensing and can write scripts in R. Ideally, users should have basic knowledge of data science methods using R.

This book presents sits, an open-source R package for land use and land cover classification using big Earth observation data.

Link: [https://e-sensing.github.io/sitsbook/](https://e-sensing.github.io/sitsbook/)


