# Journalism

## Practical R for Mass Communication and Journalism

- [Sharon Machlis](https://twitter.com/sharon000)

Welcome to this excerpt from Practical R for Mass Communication and
Journalism. In these sample chapters, you'll:

learn how to find your way around R and RStudio, see how much you can do
in just a few lines of code, start doing some basic data exploration,
and get some ideas and sample code for using R in analyzing election
results. I hope you find this excerpt useful! If you do and would like
to read more, you can order the complete book from CRC Press or Amazon.

Paid: Free samples $55

Link: [http://www.machlis.com/R4Journalists/index.html](http://www.machlis.com/R4Journalists/index.html)

## Using R for Data Journalism

- Andrew Ba Tran

This site will help you learn how to use the statistical computing and
graphics language R to enhance your data analysis and reporting process.

It was originally part of a free MOOC offered by the Knight Center at
the University of Texas

Link: [https://learn.r-journalism.com/en/](https://learn.r-journalism.com/en/)


