# Packages

## A Minimal Book Example



This is a sample book written in Markdown.

Link: [https://benmarwick.github.io/bookdown-ort/](https://benmarwick.github.io/bookdown-ort/)

## A Minimal rTorch Book

- Alfonso R. Reyes

Practically, you can do everything you could with PyTorch within the R
ecosystem.

Link: [https://f0nzie.github.io/rtorch-minimal-book/](https://f0nzie.github.io/rtorch-minimal-book/)

## An Introduction to ggplot2

- Ozancan Ozdemir

This book aims to show how you can make a well-known statistical plots by using ggplot2, and also how you can improve or customize them.

Link: [https://bookdown.org/ozancanozdemir/introduction-to-ggplot2/](https://bookdown.org/ozancanozdemir/introduction-to-ggplot2/)

## Apache Arrow R Cookbook



This cookbook aims to provide a number of recipes showing how to perform common tasks using arrow.

Link: [https://arrow.apache.org/cookbook/r/index.html](https://arrow.apache.org/cookbook/r/index.html)

## BrailleR in Action

- A. Jonathan R. Godfrey

Showing how tools that support blind R users were developed with examples. Suggestions of how blind R users should work are provided.

Link: [https://R-Resources.massey.ac.nz/BrailleRInAction/](https://R-Resources.massey.ac.nz/BrailleRInAction/)

## Circular Visualization in R

- [Zuguang GU](https://jokergoo.github.io)
- [Journal Article](https://doi.org/10.1093/bioinformatics/btu393)

This is the documentation of the circlize R package.

Link: [https://jokergoo.github.io/circlize_book/book/](https://jokergoo.github.io/circlize_book/book/)

## ComplexHeatmap Complete Reference

- [Zuguang Gu](https://github.com/jokergoo)

The ComplexHeatmap package is used to generate heatmap visualizations. It is a highly flexible tool to arrange multiple heatmaps and supports various annotation graphics for high-dimensional data. These visualizations are efficient to visualize visualizations between different sources of data sets and reveal potential patterns.

This book here contains the full documentation to using the ComplexHeatmap
package effectively with plenty of small and complex examples to help you
create your own complex heatmap data vizualization.

Link: [https://jokergoo.github.io/ComplexHeatmap-reference/book/](https://jokergoo.github.io/ComplexHeatmap-reference/book/)

## Cookbook Polars for R

- Damien Dotta

The goal of the cookbook is to provide solutions to common tasks and problems in using Polars with R. It allows R users using their usual packages to quickly get the syntax required to use Polars with R.

It is structured around side-by-side comparisons between polars, R base, dplyr, tidyr and data.table.

Link: [https://ddotta.github.io/cookbook-rpolars/](https://ddotta.github.io/cookbook-rpolars/)

## CRAN Cookbook

- Jasmine Daly
- Beni Altmann

Your go-to guide for solving common (and often recurring) issues spotted by CRAN volunteers during package submissions and re-submissions. Here, you’ll find practical “recipes” organized by different parts of the package structure.

Link: [https://contributor.r-project.org/cran-cookbook/](https://contributor.r-project.org/cran-cookbook/)

## Create, Publish, and Analyze Personal Websites Using R and RStudio

- [Danny Morris](https://r4sites-book.netlify.app/get-help.html#connect-with-me)

A free, digital handbook with step-by-step instructions for launching your own personal website using R, RStudio, and other freely available technologies including GitHub, Hugo, Netlify, and Google Analytics.

Link: [https://r4sites-book.netlify.app/](https://r4sites-book.netlify.app/)

## Data Integration, Manipulation and Visualization of Phylogenetic Trees

- [Guangchuang Yu](https://yulab-smu.top)

A guide for data integration, manipulation and visualization of phylogenetic trees using a suite of R packages, tidytree, treeio, ggtree and ggtreeExtra.

Link: [https://yulab-smu.top/treedata-book/](https://yulab-smu.top/treedata-book/)

## data.table in R The Complete Beginners Guide

- Selva Prabhakaran

data.table is a package is used for working with tabular data in R. It provides the efficient data.table object which is a much improved version of the default data.frame. It is super fast and has intuitive and terse syntax. If you know R language and haven’t picked up the data.table package yet, then this tutorial guide is a great place to start.

Link: [https://www.machinelearningplus.com/data-manipulation/datatable-in-r-complete-guide/](https://www.machinelearningplus.com/data-manipulation/datatable-in-r-complete-guide/)

## Deep Learning and Scientific Computing with R torch

- [Sigrid Keydana](https://divergences.xyz/)

This is a book about torch, the R interface to PyTorch. PyTorch, as of this writing, is one of the major deep-learning and scientific-computing frameworks, widely used across industries and areas of research. With torch, you get to access its rich functionality directly from R, with no need to install, let alone learn, Python.

Link: [https://skeydan.github.io/Deep-Learning-and-Scientific-Computing-with-R-torch/](https://skeydan.github.io/Deep-Learning-and-Scientific-Computing-with-R-torch/)

## Flexible Imputation of Missing Data

- Stef van Buuren

Multiple imputation of missing data has become one of the great academic industries. Many analysts now employ multiple imputation on a regular basis as a generic solution to the omnipresent missing-data problem, and a substantial group of practitioners are doing the calculations in mice. This book aspires to combine a state-of-the-art overview of the field with a set of how-to instructions for practical data analysis.

Link: [https://stefvanbuuren.name/fimd/](https://stefvanbuuren.name/fimd/)

## ggplot2 Elegant Graphics for Data Analysis

- Hadley Wickham

ggplot2 is an R package for producing statistical, or data, graphics.
Unlike most other graphics packages, ggplot2 has an underlying grammar,
based on the Grammar of Graphics (Wilkinson 2005), that allows you to
compose graphs by combining independent components. This makes ggplot2
powerful. Rather than being limited to sets of pre-defined graphics, you
can create novel graphics that are tailored to your specific problem.

Link: [https://ggplot2-book.org/](https://ggplot2-book.org/)

## GT Cookbook

- [Thomas Mock](https://twitter.com/thomas_mock)

This cookbook attempts to walk through many of the example usecases for gt, and provide useful commentary around the use of the various gt functions. The full gt documentation has other more succinct examples and full function arguments.

For advanced use cases, make sure to check out the Advanced Cookbook

Link: [https://themockup.blog/static/resources/gt-cookbook.html](https://themockup.blog/static/resources/gt-cookbook.html)

## GT Cookbook Advanced

- [Thomas Mock](https://twitter.com/thomas_mock)

This cookbook attempts to walk through many of the advanced applications for gt, and provide useful commentary around the use of the various gt functions. The full gt documentation has other more succinct examples and full function arguments.

Link: [https://themockup.blog/static/resources/gt-cookbook-advanced.html](https://themockup.blog/static/resources/gt-cookbook-advanced.html)

## Highcharter Cookbook

- Tom Bishop

Highcharter is an R implementation of the highcharts javascript library, enabled by R’s htmlwidgets package. Most of the highcharts functionality is implemented through highcharter however the documentation is a little light. This guide will provide examples on how to create and customise various graphs whilst providing some tips on how to think about the package that will help you build and debug your more ambitious charts.

Link: [https://www.tmbish.me/lab/highcharter-cookbook/](https://www.tmbish.me/lab/highcharter-cookbook/)

## knitr

- [Yihui Xie](https://yihui.org/)

Dynamic documents with R and knitr!

The knitr package was designed to be a transparent engine for dynamic
report generation with R, solve some long-standing problems in Sweave,
and combine features in other add-on packages into one package.

Link: [https://yihui.org/knitr/](https://yihui.org/knitr/)

## Marginal Effects Zoo

- [Vincent Arel-Bundock](https://arelbundock.com)

It includes over 30 chapters overs a wide range of topics, including how the marginaleffects package can facilitate the analysis of: Experiments, Observational data, Causal inference with G-Computation, Machine learning models, Bayesian modeling, Multilevel regression with post-stratification (MRP), Missing data, Matching, Inverse probability weighting, and Conformal prediction.

Link: [https://marginaleffects.com](https://marginaleffects.com)

## mlr3 book

- [Michel Lang](https://twitter.com/michellangts)

The mlr3 package and
[ecosystem](https://github.com/mlr-org/mlr3/wiki/Extension-Packages)
provide a generic, object-oriented, and extensible framework for
classification, regression, survival analysis, and other machine
learning tasks for the R language. They do not implement any learners,
but provide a unified interface to many existing learners in R.

Link: [https://mlr3book.mlr-org.com/](https://mlr3book.mlr-org.com/)

## Multi-state modelling with msm: a practical course

- [Christopher Jackson](https://chjackson.github.io)

An introduction to the use of the msm R package for fitting and predicting from multi-state models for intermittently observed data, in typical medical applications.

Link: [https://chjackson.github.io/msm/msmcourse/](https://chjackson.github.io/msm/msmcourse/)

## officeverse

- [David Gohel](https://twitter.com/davidgohel)

This book deals with reporting from R with the packages {officer}, {officedown}, {flextable}, {rvg} and {mschart}. These packages have been developed to facilitate the production of Word documents and PowerPoint presentations from and with R. It was written specifically to offer a competitive solution to SAS ODS for tabular and graphical reporting.

Link: [https://ardata-fr.github.io/officeverse/](https://ardata-fr.github.io/officeverse/)

## pipeR Tutorial

- [Kun Ren](https://twitter.com/renkun_ken)

pipeR is an R package that helps you better organize your code in pipeline built with %>>%, Pipe() or pipeline(), which is much easier to read, write, and maintain.

Link: [https://renkun-ken.github.io/pipeR-tutorial/](https://renkun-ken.github.io/pipeR-tutorial/)

## R bookdownplus Textbook

- Peng Zhao

‘bookdownplus’ is an extension of ‘bookdown’. It is a collection of multiple templates, which I have been collecting since years ago on the basis of LaTeX, and have been tailoring them so that I can work happily under the umbrella of ‘bookdown’. ‘bookdownplus’ helps you (and me) write varied types of books and documents. This book you are reading at the moment was exactly produced by ‘bookdownplus’.

Link: [https://bookdown.org/baydap/bookdownplus/](https://bookdown.org/baydap/bookdownplus/)

## R Function a Day

- [Indrajeet Patil](https://twitter.com/patilindrajeets)

A book that collects (and provides an easy way to access and search) tweets from R Function A Day account that maintained for 1 year (from 24.01.2021 to 24.01.2022).

Link: [https://bookdown.org/IndrajeetPatil/R-Function-A-Day-book/](https://bookdown.org/IndrajeetPatil/R-Function-A-Day-book/)

## Rcpp for everyone

- Masaki E. Tsuda

Rcpp is a package that enables you to implement R functions in C++. It
is easy to use even without deep knowledge of C++, because it is
implemented so as to write your C++ code in a style similar to R. And
Rcpp does not sacrifice execution speed for the ease of use, anyone can
get high performance outcome.

This document focuses on providing necessary information to users who
are not familiar with C++. Therefore, in some cases, I explain usage of
Rcpp conceptually rather than describing accurately from the viewpoint
of C++, so that I hope readers can easily understand it.

Link: [https://teuder.github.io/rcpp4everyone_en/](https://teuder.github.io/rcpp4everyone_en/)

## reactablefmtr Cookbook

- [Kyle Cuilla](https://twitter.com/kc_analytics)

A high-level overview of the functions and styling customization options available in {reactablefmtr}.

Link: [https://kcuilla.github.io/reactablefmtr/articles/reactablefmtr_cookbook.html](https://kcuilla.github.io/reactablefmtr/articles/reactablefmtr_cookbook.html)

## rlist Tutorial

- [Kun Ren](https://renkun.me)

rlist is a set of tools for working with list objects. Its goal is to make it easier to work with lists by providing a wide range of functions on non-tabular data stored in them. This package supports filtering, mapping, grouping, sorting, updating, searching and many other functions. It is pipe-friendly and strongly recommends functional programming style in list operations. This tutorial serves as complete guide to using rlist functionality to work with non-tabular data.

Link: [https://renkun-ken.github.io/rlist-tutorial/](https://renkun-ken.github.io/rlist-tutorial/)

## Scaling Up With R and Arrow

- [Nic Crane](https://thisisnic.github.io/about/)
- [Jonathan Keane](https://twitter.com/jonkeane?lang=en)
- [Neal Richardson](https://github.com/nealrichardson)

Arrow allows you to work with larger-than-memory data directly from R without needing to set up additional infrastructure. It implements the dplyr API, which means that if you are familiar with dplyr functions, you can use those same functions with arrow and don’t have to learn a whole new framework.

Link: [https://arrowrbook.com/](https://arrowrbook.com/)

## Shiny App-Packages

- Martin Frigaard

This book is a resource to help ‘connect the dots’ between building scalable Shiny applications and writing R packages. Adopting R package development practices in the early stages of your Shiny app will improve the reusability, maintainability, and shareability of all your hard work.

Link: [https://mjfrigaard.github.io/shiny-app-pkgs/](https://mjfrigaard.github.io/shiny-app-pkgs/)

## Targeted Learning in R: Causal Data Science with the tlverse Software Ecosystem

- [Mark van der Laan](https://statistics.berkeley.edu/people/mark-van-der-laan)
- [Jeremy Coyle](https://scholar.google.com/citations?user=DyFxaxAAAAAJ)
- [Nima Hejazi](https://nimahejazi.org)
- [Ivana Malenica](https://imalenica.github.io)
- [Rachael Phillips](https://scholar.google.com/citations?user=vD1fxpEAAAAJ)
- [Alan Hubbard](https://vcresearch.berkeley.edu/faculty/alan-hubbard)

It is a fully reproducible, open-source, electronic handbook for applying Targeted Learning methodology in practice using the software stack provided by the tlverse ecosystem.

Link: [https://tlverse.org/tlverse-handbook/](https://tlverse.org/tlverse-handbook/)

## The caret Package

- Max Kuhn

The caret package (short for Classification And REgression Training) is
a set of functions that attempt to streamline the process for creating
predictive models.

Link: [https://topepo.github.io/caret/index.html](https://topepo.github.io/caret/index.html)

## The Data Validation Cookbook

- [Mark P.J. van der Loo](https://twitter.com/markvdLoo)

The purposes of this book include demonstrating the main tools and workflows of the validate package, giving examples of common data validation tasks, and showing how to analyze data validation results.

Link: [https://data-cleaning.github.io/validate/](https://data-cleaning.github.io/validate/)

## The Grammar of Experimental Designs

- [Emi Tanaka](https://emitanaka.org)

An book about designing experiments using the eddible package.

Link: [https://emitanaka.org/edibble-book/index.html](https://emitanaka.org/edibble-book/index.html)

## The lidR package

- Jean-Romain Roussel
- Tristan R.H. Goodbody
- Piotr Tompalski

lidR is an R package for manipulating and visualizating airborne laser scanning (ALS) data with an emphasis on forestry applications. The package is entirely open source and is integrated within the geospatial R ecosytem (i.e. raster, sp, sf, rgdal etc.). This guide has been written to help both the ALS novice, as well as seasoned point cloud processing veterans.

Link: [https://jean-romain.github.io/lidRbook/](https://jean-romain.github.io/lidRbook/)

## The targets R Package Design Specification

- [Will Landau](https://fosstodon.org/@landau)

targets has an elaborate structure to support its advanced features while ensuring decent performance. This bookdown site is a design specification to explain the major aspects of the internal architecture, including the data storage model, object oriented design, and orchestration and branching model

Link: [https://books.ropensci.org/targets-design/index.html](https://books.ropensci.org/targets-design/index.html)

## The targets R Package User Manual

- Will Landau

The targets package is a Make-like pipeline toolkit for Statistics and data science in R. With targets, you can maintain a reproducible workflow without repeating yourself. targets learns how your pipeline fits together, skips costly runtime for tasks that are already up to date, runs only the necessary computation, supports implicit parallel computing, abstracts files as R objects, and shows tangible evidence that the results match the underlying code and data.

Link: [https://books.ropensci.org/targets/](https://books.ropensci.org/targets/)

## The Tidyverse Cookbook

- Edited by Garrett Grolemund

This book collects code recipes for doing data science with R's
tidyverse. Each recipe solves a single common task, with a minimum of
discussion.

Link: [https://rstudio-education.github.io/tidyverse-cookbook/](https://rstudio-education.github.io/tidyverse-cookbook/)


