# Psychology

## An introduction to psychometric theory with applications in R

- William Revelle

My course in psychometric theory, on which much of this book is based, was inspired by a course of the same name by Warren Norman. The organizational structure of this text owes a great deal to the structure of Warren's course. Warren introduced me, as well as a generation of graduate students at the University of Michigan, to the role of theory and measurement in the study of psychology.

Link: [https://personality-project.org/r/book/](https://personality-project.org/r/book/)

## Learning statistics with R A tutorial for psychology students and other beginners

- [Danielle Navarro](https://twitter.com/djnavarro)

Learning Statistics with R covers the contents of an introductory statistics class, as typically taught to undergraduate psychology students, focusing on the use of the R statistical software. The book discusses how to get started in R as well as giving an introduction to
data manipulation and writing scripts. From a statistical perspective, the book discusses descriptive statistics and graphing ﬁrst, followed by chapters on probability theory, sampling and estimation, and null hypothesis testing. After introducing the theory, the book covers the
analysis of contingency tables, t-tests, ANOVAs and regression. Bayesian statistics are covered at the end of the book.

Link: [https://learningstatisticswithr-bookdown.netlify.app/](https://learningstatisticswithr-bookdown.netlify.app/)

## Modern Statistical Methods for Psychology

- [Mine Çetinkaya-Rundel](https://mine-cr.com/)
- [Jo Hardin](https://research.pomona.edu/johardin/)

This book is intended to help psychology students build a foundation for statistical thinking and methods. This textbook consists of 3 main parts: (1) descriptive statistics, (2) foundations for inference, and (3) statistical inference. Each part contains multiple chapters. Each chapter ends with a review section which contains a chapter summary as well as a list of key terms introduced in the chapter.

Link: [https://bookdown.org/gregcox7/ims_psych/](https://bookdown.org/gregcox7/ims_psych/)

## Principles of Psychological Assessment: With Applied Examples in R

- [Isaac Petersen](https://psychology.uiowa.edu/people/isaac-petersen)

This book highlights the principles of psychological assessment to help researchers and clinicians better develop, evaluate, administer, score, integrate, and interpret psychological assessments. It discusses psychometrics (reliability and validity), the assessment of various psychological domains (behavior, personality, intellectual functioning), various measurement methods (e.g., questionnaires, observations, interviews, biopsychological assessments, performance-based assessments), and emerging analytical frameworks to evaluate and improve assessment including: generalizability theory, structural equation modeling, item response theory, and signal detection theory. The text also discusses ethics, test bias, and cultural and individual diversity. The book provides practical data and analysis examples in R to help people better understand principles of psychological assessment and how to apply them. The book uses the freely available [petersenlab](https://doi.org/10.32614/CRAN.package.petersenlab) package for R.

Link: [https://isaactpetersen.github.io/Principles-Psychological-Assessment/](https://isaactpetersen.github.io/Principles-Psychological-Assessment/)

Physical copy available: [https://www.routledge.com/Principles-of-Psychological-Assessment-With-Applied-Examples-in-R/Petersen/p/book/9781032413068](https://www.routledge.com/Principles-of-Psychological-Assessment-With-Applied-Examples-in-R/Petersen/p/book/9781032413068)

## Psychometrics in Exercises using R and RStudio

- [Anna Brown](https://annabrown.name/)

Provides a comprehensive set of exercises for practicing all major Psychometric techniques using R and RStudio. The exercises are based on real data from research studies and operational assessments, and provide step-by-step guides that an instructor can use to teach students, or readers can use to learn independently. Each exercise includes a worked example illustrating data analysis steps and teaching how to interpret results and make analysis decisions, and self-test questions that readers can attempt to check own understanding.

Link: [https://bookdown.org/annabrown/psychometricsR/](https://bookdown.org/annabrown/psychometricsR/)

## R Programming for Psychometrics

- [Susu Zhang](https://psychology.illinois.edu/directory/profile/szhan105)

A good test developer should not only be well-versed with measurement theory and psychometric methods. Nowadays, programming skills are also essential. So, the aim of this book is to introduce R to you and improve your data wrangling and functional programming skills.

Link: [https://bookdown.org/sz_psyc490/r4psychometics/](https://bookdown.org/sz_psyc490/r4psychometics/)

## Reproducible statistics for psychologists with R: Lab Tutorials

- Matthew J. C. Crump

This is a series of labs/tutorials for a two-semester graduate-level statistics sequence in Psychology @ Brooklyn College of CUNY. The goal of these tutorials is to 1) develop a deeper conceptual understanding of the principles of statistical analysis and inference; and 2) develop practical skills for data-analysis, such as using the increasingly popular statistical software environment R to code reproducible analyses.

Link: [https://crumplab.com/rstatsforpsych/index.html](https://crumplab.com/rstatsforpsych/index.html)


